<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AccountPushSetting.proto

namespace GPBMetadata;

class AccountPushSetting
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a010a184163636f756e745075736853657474696e672e70726f746f12" .
            "0b6d736767616d65646174612a540a124163636f756e7450757368536574" .
            "74696e67120d0a094150535f426c6f636b1000120d0a094150535f4e6967" .
            "6874100112100a0c4150535f4461796c696768741002120e0a0a4150535f" .
            "416c77617973100342130a11636f6d2e66656c616e69612e6d736c646262" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

