<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AccountMarketType.proto

namespace GPBMetadata;

class AccountMarketType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a174163636f756e744d61726b6574547970652e70726f746f120b" .
            "6d736767616d65646174612a700a114163636f756e744d61726b65745479" .
            "706512190a154163636f756e744d61726b6574547970654e554c4c100012" .
            "100a0c414d545f41707053746f7265100b12110a0d414d545f506c617953" .
            "746f7265100c120b0a07414d545f455443100d120e0a0a414d545f416d61" .
            "7a6f6e101f42130a11636f6d2e66656c616e69612e6d736c646262067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

