<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleEndResultType.proto

namespace GPBMetadata;

class BattleEndResultType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8010a19426174746c65456e64526573756c74547970652e70726f746f" .
            "120b6d736767616d65646174612a610a13426174746c65456e6452657375" .
            "6c7454797065120d0a09424552545f4e6f6e651000120d0a09424552545f" .
            "447261771001120d0a09424552545f4c6f73651002120c0a08424552545f" .
            "57696e1003120f0a0b424552545f476976655570100442130a11636f6d2e" .
            "66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

