<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CaptureFestivalType.proto

namespace GPBMetadata;

class CaptureFestivalType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5010a1943617074757265466573746976616c547970652e70726f746f" .
            "120b6d736767616d65646174612a5e0a1343617074757265466573746976" .
            "616c54797065120c0a084346545f4e6f6e651000120b0a074346545f4576" .
            "651001120f0a0b4346545f436170747572651002120e0a0a4346545f4669" .
            "6e616c651003120b0a074346545f416c6c100442130a11636f6d2e66656c" .
            "616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

