<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClanBattleType.proto

namespace GPBMetadata;

class ClanBattleType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84010a14436c616e426174746c65547970652e70726f746f120b6d7367" .
            "67616d65646174612a420a0e436c616e426174746c655479706512160a12" .
            "436c616e426174746c65547970654e554c4c1000120b0a074342545f4356" .
            "451001120b0a074342545f435643100242130a11636f6d2e66656c616e69" .
            "612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

