<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClanMemberGrade.proto

namespace GPBMetadata;

class ClanMemberGrade
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a15436c616e4d656d62657247726164652e70726f746f120b6d73" .
            "6767616d65646174612a590a0f436c616e4d656d62657247726164651212" .
            "0a0e434d475f41707072656e746963651000120e0a0a434d475f4d656d62" .
            "6572100112120a0e434d475f566963654d61737465721002120e0a0a434d" .
            "475f4d6173746572100342130a11636f6d2e66656c616e69612e6d736c64" .
            "62620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

