<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendState.proto

namespace GPBMetadata;

class FriendState
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88010a11467269656e6453746174652e70726f746f120b6d736767616d" .
            "65646174612a490a0b467269656e64537461746512100a0c46535f526571" .
            "756573746564100012110a0d46535f4d616b65467269656e64100112150a" .
            "1146535f57616974546f526573706f6e7365100242130a11636f6d2e6665" .
            "6c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

