<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MonsterRuneSlotShape.proto

namespace GPBMetadata;

class MonsterRuneSlotShape
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a1a4d6f6e7374657252756e65536c6f7453686170652e70726f74" .
            "6f120b6d736767616d65646174612a6f0a144d6f6e7374657252756e6553" .
            "6c6f745368617065120d0a094d5253535f4e6f6e65100012110a0d4d5253" .
            "535f547269616e676c65100112120a0e4d5253535f52656374616e676c65" .
            "100212100a0c4d5253535f4469616d6f6e641003120f0a084d5253535f41" .
            "6c6c10cec2f10542130a11636f6d2e66656c616e69612e6d736c64626206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

