<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgBingoCompleteEventReward.proto

namespace GPBMetadata;

class MsgBingoCompleteEventReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgReward::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0adb010a214d736742696e676f436f6d706c6574654576656e7452657761" .
            "72642e70726f746f120b6d736767616d6564617461228b010a1b4d736742" .
            "696e676f436f6d706c6574654576656e7452657761726412140a0c636f6d" .
            "706c6574655f636e7418012001280d12260a067265776172641802200128" .
            "0b32162e6d736767616d65646174612e4d7367526577617264122e0a0e73" .
            "70656369616c5f72657761726418032001280b32162e6d736767616d6564" .
            "6174612e4d736752657761726442130a11636f6d2e66656c616e69612e6d" .
            "736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

