<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgBattleEndScenario.proto

namespace GPBMetadata;

class MsgBattleEndScenario
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgDataTypeUidAndAmount::initOnce();
        \GPBMetadata\BattleEndResultType::initOnce();
        \GPBMetadata\MsgBattleMonsterStat::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97030a1a4d7367426174746c65456e645363656e6172696f2e70726f74" .
            "6f120b6d736767616d65646174611a19426174746c65456e64526573756c" .
            "74547970652e70726f746f1a1a4d7367426174746c654d6f6e7374657253" .
            "7461742e70726f746f2297020a144d7367426174746c65456e645363656e" .
            "6172696f12110a09626174746c655f696418012001280412330a05697465" .
            "6d7318022003280b32242e6d736767616d65646174612e4d736744617461" .
            "54797065556964416e64416d6f756e7412300a06726573756c7418032001" .
            "280e32202e6d736767616d65646174612e426174746c65456e6452657375" .
            "6c745479706512120a0a637572725f726f756e6418042001280d120f0a07" .
            "7265766976616c18052001280d12110a096d6f6e5f646561746818062001" .
            "280d12110a096d6f6e5f636f756e7418072001280d123a0a0f6d6f6e5f72" .
            "6573756c745f6461746118082003280b32212e6d736767616d6564617461" .
            "2e4d7367426174746c654d6f6e737465725374617442130a11636f6d2e66" .
            "656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

