<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgCrystalReward.proto

namespace GPBMetadata;

class MsgCrystalReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8c010a164d73674372797374616c5265776172642e70726f746f120b6d" .
            "736767616d656461746122480a104d73674372797374616c526577617264" .
            "12160a0e6372797374616c5f72657761726418012001280d121c0a146372" .
            "797374616c5f626f6e75735f72657761726418022001280d42130a11636f" .
            "6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

