<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgClanAttendanceReward.proto

namespace GPBMetadata;

class MsgClanAttendanceReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0010a1d4d7367436c616e417474656e64616e63655265776172642e70" .
            "726f746f120b6d736767616d656461746122550a174d7367436c616e4174" .
            "74656e64616e6365526577617264120b0a03756964180120012807120b0a" .
            "036d696e18022001280d120b0a036d617818032001280d12130a0b626f6e" .
            "75735f706f696e7418042001280d42130a11636f6d2e66656c616e69612e" .
            "6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

