<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgClanSeason.proto

namespace GPBMetadata;

class MsgClanSeason
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0add010a134d7367436c616e536561736f6e2e70726f746f120b6d736767" .
            "616d6564617461229b010a0d4d7367436c616e536561736f6e120b0a0375" .
            "6964180120012807120b0a0369647818022001280d12110a096f70656e5f" .
            "6461746518032001280412120a0a636c6f73655f64617465180420012804" .
            "12110a0973746167655f756964180520012807121a0a126376635f6d656d" .
            "6265725f636e745f6d696e18062001280d121a0a126376635f6d656d6265" .
            "725f636e745f6d617818072001280d42130a11636f6d2e66656c616e6961" .
            "2e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

