<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgCustomBtnSound.proto

namespace GPBMetadata;

class MsgCustomBtnSound
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a85010a174d7367437573746f6d42746e536f756e642e70726f746f120b" .
            "6d736767616d656461746122400a114d7367437573746f6d42746e536f75" .
            "6e64120b0a03756964180120012807120c0a047061746818022001280912" .
            "100a08736e645f7479706518032001280942130a11636f6d2e66656c616e" .
            "69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

