<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgClanFestivalGiftSendData.proto

namespace GPBMetadata;

class MsgClanFestivalGiftSendData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UserCharType::initOnce();
        \GPBMetadata\UserCharSkinType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae7020a214d7367436c616e466573746976616c4769667453656e644461" .
            "74612e70726f746f120b6d736767616d65646174611a1655736572436861" .
            "72536b696e547970652e70726f746f22ff010a1b4d7367436c616e466573" .
            "746976616c4769667453656e6444617461120f0a07757365725f69641801" .
            "2001280412160a0e67616368615f6576656e745f6964180220012804120c" .
            "0a046e616d65180320012809122c0a09636861725f747970651804200128" .
            "0e32192e6d736767616d65646174612e5573657243686172547970651230" .
            "0a09736b696e5f7479706518052001280e321d2e6d736767616d65646174" .
            "612e5573657243686172536b696e54797065121d0a15757365725f70726f" .
            "66696c655f69636f6e5f75696418062001280d12110a0969735f6d617374" .
            "657218072001280812170a0f73656e645f676966745f636f756e74180820" .
            "01280d42130a11636f6d2e66656c616e69612e6d736c6462620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

