<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgCaptureFestivalRankReward.proto

namespace GPBMetadata;

class MsgCaptureFestivalRankReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUidAndAmount::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac7010a224d736743617074757265466573746976616c52616e6b526577" .
            "6172642e70726f746f120b6d736767616d656461746122770a1c4d736743" .
            "617074757265466573746976616c52616e6b526577617264120b0a037569" .
            "64180120012807120d0a05677261646518022001280d122c0a0672657761" .
            "726418032001280b321c2e6d736767616d65646174612e4d736755696441" .
            "6e64416d6f756e74120d0a057469746c6518042001280742130a11636f6d" .
            "2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

