<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgCaptureKingUserHistory.proto

namespace GPBMetadata;

class MsgCaptureKingUserHistory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5020a1f4d7367436170747572654b696e6755736572486973746f7279" .
            "2e70726f746f120b6d736767616d656461746122f7010a194d7367436170" .
            "747572654b696e6755736572486973746f727912130a0b7265776172645f" .
            "6461746518012001280412180a1063756d756c61746976655f706f696e74" .
            "18022001280d121c0a14726172655f315f636170747572655f636f756e74" .
            "18032001280d121c0a14726172655f325f636170747572655f636f756e74" .
            "18042001280d121c0a14726172655f335f636170747572655f636f756e74" .
            "18052001280d121c0a14726172655f345f636170747572655f636f756e74" .
            "18062001280d121d0a156c6173745f63756d756c61746976655f706f696e" .
            "7418072001280d12140a0c736561736f6e5f696e64657818082001280d42" .
            "130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

