<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgClientDeviceInfo.proto

namespace GPBMetadata;

class MsgClientDeviceInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\AccountOSType::initOnce();
        \GPBMetadata\AccountMarketType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad8020a194d7367436c69656e74446576696365496e666f2e70726f746f" .
            "120b6d736767616d65646174611a174163636f756e744d61726b65745479" .
            "70652e70726f746f22f7010a134d7367436c69656e74446576696365496e" .
            "666f120e0a0664657669636518012001280912260a026f7318022001280e" .
            "321a2e6d736767616d65646174612e4163636f756e744f53547970651212" .
            "0a0a6f735f76657273696f6e180320012809122e0a066d61726b65741804" .
            "2001280e321e2e6d736767616d65646174612e4163636f756e744d61726b" .
            "65745479706512100a086c616e6775616765180520012809120f0a07636f" .
            "756e74727918062001280912120a0a707573685f746f6b656e1807200128" .
            "0912140a0c6164766572746973655f696418082001280912170a0f737472" .
            "696e675f74696d657a6f6e6518092001280942130a11636f6d2e66656c61" .
            "6e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

