<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgClanLastSeasonChampion.proto

namespace GPBMetadata;

class MsgClanLastSeasonChampion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad010a1f4d7367436c616e4c617374536561736f6e4368616d70696f6e" .
            "2e70726f746f120b6d736767616d656461746122600a194d7367436c616e" .
            "4c617374536561736f6e4368616d70696f6e120f0a07636c616e5f696418" .
            "012001280412110a0973746167655f756964180220012807120c0a046e61" .
            "6d6518032001280912110a09656d626c656d5f696418042001280d42130a" .
            "11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

