<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgDataTypeUidAndAmount.proto

namespace GPBMetadata;

class MsgDataTypeUidAndAmount
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\GlobalDataType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab1010a1d4d73674461746154797065556964416e64416d6f756e742e70" .
            "726f746f120b6d736767616d656461746122660a174d7367446174615479" .
            "7065556964416e64416d6f756e74122e0a09646174615f74797065180120" .
            "01280e321b2e6d736767616d65646174612e476c6f62616c446174615479" .
            "7065120b0a03756964180220012807120e0a06616d6f756e741803200128" .
            "0d42130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

