<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgDungeonStage.proto

namespace GPBMetadata;

class MsgDungeonStage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BattleType::initOnce();
        \GPBMetadata\MsgGeneralDungeonStageInfo::initOnce();
        \GPBMetadata\MsgFriendDungeonStageInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af2030a154d736744756e67656f6e53746167652e70726f746f120b6d73" .
            "6767616d65646174611a204d736747656e6572616c44756e67656f6e5374" .
            "616765496e666f2e70726f746f1a1f4d7367467269656e6444756e67656f" .
            "6e5374616765496e666f2e70726f746f22eb020a0f4d736744756e67656f" .
            "6e5374616765120b0a0375696418012001280712110a0973746167655f69" .
            "647818022001280d120c0a046e616d65180320012807120c0a0464657363" .
            "18042001280712140a0c73746167655f707265666162180520012809122c" .
            "0a0b626174746c655f7479706518062001280e32172e6d736767616d6564" .
            "6174612e426174746c655479706512190a1173746167655f7469746c655f" .
            "696d61676518082001280912180a1073746167655f6d61726b5f696d6167" .
            "6518092001280912110a09737562737461676573180c2003280712480a17" .
            "67656e6572616c44756e67656f6e5374616765496e666f180d2001280b32" .
            "272e6d736767616d65646174612e4d736747656e6572616c44756e67656f" .
            "6e5374616765496e666f12460a16667269656e6444756e67656f6e537461" .
            "6765496e666f180e2001280b32262e6d736767616d65646174612e4d7367" .
            "467269656e6444756e67656f6e5374616765496e666f42130a11636f6d2e" .
            "66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

