<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgEnemyMonster.proto

namespace GPBMetadata;

class MsgEnemyMonster
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d010a154d7367456e656d794d6f6e737465722e70726f746f120b6d73" .
            "6767616d6564617461224a0a0f4d7367456e656d794d6f6e737465721219" .
            "0a1173746167655f6d6f6e737465725f756964180120012807121c0a1464" .
            "726f705f6974656d5f6b696c6c5f696e64657818022001280d42130a1163" .
            "6f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

