<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgEmbeddedGameString.proto

namespace GPBMetadata;

class MsgEmbeddedGameString
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgLocalizedString::initOnce();
        \GPBMetadata\MsgUid::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac3010a1b4d7367456d62656464656447616d65537472696e672e70726f" .
            "746f120b6d736767616d65646174611a0c4d73675569642e70726f746f22" .
            "6c0a154d7367456d62656464656447616d65537472696e6712300a077374" .
            "72696e677318012003280b321f2e6d736767616d65646174612e4d73674c" .
            "6f63616c697a6564537472696e6712210a047569647318022003280b3213" .
            "2e6d736767616d65646174612e4d736755696442130a11636f6d2e66656c" .
            "616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

