<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgGiftTemplate.proto

namespace GPBMetadata;

class MsgGiftTemplate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5020a154d73674769667454656d706c6174652e70726f746f120b6d73" .
            "6767616d656461746122f1010a0f4d73674769667454656d706c61746512" .
            "0b0a03756964180120012807123b0a047479706518022001280e322d2e6d" .
            "736767616d65646174612e4d73674769667454656d706c6174652e476966" .
            "7454656d706c61746554797065120b0a036d7367180320012807120c0a04" .
            "6465736318042001280722790a104769667454656d706c61746554797065" .
            "12180a144769667454656d706c617465547970654e554c4c100012140a10" .
            "536572766572496e7370656374696f6e100112110a0d5365727665724661" .
            "696c757265100212090a054576656e74100b12090a054172656e61100c12" .
            "0c0a08496e66696e697465100d42130a11636f6d2e66656c616e69612e6d" .
            "736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

