<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgItemTypeClanFestivalGift.proto

namespace GPBMetadata;

class MsgItemTypeClanFestivalGift
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8010a214d73674974656d54797065436c616e466573746976616c4769" .
            "66742e70726f746f120b6d736767616d656461746122590a1b4d73674974" .
            "656d54797065436c616e466573746976616c4769667412190a1172616e64" .
            "6f6d5f7265776172645f756964180120012807121f0a1772616e646f6d5f" .
            "6865726f5f657373656e63655f75696418022001280742130a11636f6d2e" .
            "66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

