<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgInputLengthCondition.proto

namespace GPBMetadata;

class MsgInputLengthCondition
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ace030a1d4d7367496e7075744c656e677468436f6e646974696f6e2e70" .
            "726f746f120b6d736767616d65646174612282030a174d7367496e707574" .
            "4c656e677468436f6e646974696f6e22340a08557365724e616d6512100a" .
            "0c557365724e616d654e554c4c1000120a0a06554e5f4d494e1004120a0a" .
            "06554e5f4d4158100c22340a0853656c664465736312100a0c53656c6644" .
            "6573634e554c4c1000120a0a0653445f4d494e1002120a0a0653445f4d41" .
            "58102822350a08436c616e4465736312100a0c436c616e446573634e554c" .
            "4c1000120a0a0643445f4d494e1014120b0a0643445f4d4158109003224a" .
            "0a12436c616e4368617474696e674e6f74696365121a0a16436c616e4368" .
            "617474696e674e6f746963654e554c4c1000120b0a0743434e5f4d494e10" .
            "02120b0a0743434e5f4d41581028223a0a0b436c616e436f6d6d656e7412" .
            "130a0f436c616e436f6d6d656e744e554c4c1000120a0a0643435f4d494e" .
            "1002120a0a0643435f4d41581028223c0a0a435643436f6d6d656e741212" .
            "0a0e435643436f6d6d656e744e554c4c1000120c0a08435643435f4d494e" .
            "1002120c0a08435643435f4d4158102842130a11636f6d2e66656c616e69" .
            "612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

