<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgJojeShopSlot.proto

namespace GPBMetadata;

class MsgJojeShopSlot
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80010a154d73674a6f6a6553686f70536c6f742e70726f746f120b6d73" .
            "6767616d6564617461223d0a0f4d73674a6f6a6553686f70536c6f74120b" .
            "0a03756964180120012807120b0a036c657618022001280d12100a08736c" .
            "6f745f636e7418032001280d42130a11636f6d2e66656c616e69612e6d73" .
            "6c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

