<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgMonthlyMonsterGroupData.proto

namespace GPBMetadata;

class MsgMonthlyMonsterGroupData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgMonthlyMonsterData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a204d73674d6f6e74686c794d6f6e7374657247726f7570446174" .
            "612e70726f746f120b6d736767616d656461746122670a1a4d73674d6f6e" .
            "74686c794d6f6e7374657247726f757044617461120b0a03756964180120" .
            "012807123c0a106d6f6e74686c795f6d6f6e737465727318022003280b32" .
            "222e6d736767616d65646174612e4d73674d6f6e74686c794d6f6e737465" .
            "724461746142130a11636f6d2e66656c616e69612e6d736c646262067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

