<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgMonsterCostumeBundle.proto

namespace GPBMetadata;

class MsgMonsterCostumeBundle
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgPrice::initOnce();
        \GPBMetadata\MsgShopItem::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acd020a1d4d73674d6f6e73746572436f7374756d6542756e646c652e70" .
            "726f746f120b6d736767616d65646174611a114d736753686f704974656d" .
            "2e70726f746f22ee010a174d73674d6f6e73746572436f7374756d654275" .
            "6e646c65120b0a03756964180120012807120c0a046e616d651802200128" .
            "0712180a10636f7374756d5f6974656d5f7569647318032003280712240a" .
            "05707269636518042001280b32152e6d736767616d65646174612e4d7367" .
            "5072696365122f0a046d61726b18052001280e32212e6d736767616d6564" .
            "6174612e4d736753686f704974656d2e4d61726b54797065120d0a056465" .
            "73633318062001280712110a096f70656e5f646174651807200128041212" .
            "0a0a636c6f73655f6461746518082001280412110a09646565705f6c696e" .
            "6b18092001280942130a11636f6d2e66656c616e69612e6d736c64626206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

