<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgMonsterSlotData.proto

namespace GPBMetadata;

class MsgMonsterSlotData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5020a184d73674d6f6e73746572536c6f74446174612e70726f746f12" .
            "0b6d736767616d656461746122de010a124d73674d6f6e73746572536c6f" .
            "7444617461120d0a05696e64657818012001280d120e0a06736c6f745f31" .
            "180220012804120e0a06736c6f745f32180320012804120e0a06736c6f74" .
            "5f33180420012804120e0a06736c6f745f34180520012804120e0a06736c" .
            "6f745f3518062001280412170a0f667269656e645f736c6f745f69647818" .
            "072001280d12160a0e667269656e645f757365725f696418082001280412" .
            "1b0a13737570706f72745f6d6f6e737465725f69647818092001280d121b" .
            "0a13737570706f72745f6d6f6e737465725f756964180a2001280742130a" .
            "11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

