<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgSpecialGuardianDungeonData.proto

namespace GPBMetadata;

class MsgSpecialGuardianDungeonData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgSpecialGuardianDungeonDate::initOnce();
        \GPBMetadata\MsgFriendDungeonFindHistory::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5020a234d73675370656369616c477561726469616e44756e67656f6e" .
            "446174612e70726f746f120b6d736767616d65646174611a214d73674672" .
            "69656e6444756e67656f6e46696e64486973746f72792e70726f746f22c0" .
            "010a1d4d73675370656369616c477561726469616e44756e67656f6e4461" .
            "746112520a1e7370656369616c5f677561726469616e5f64756e67656f6e" .
            "5f646174657318012003280b322a2e6d736767616d65646174612e4d7367" .
            "5370656369616c477561726469616e44756e67656f6e44617465124b0a19" .
            "7370656369616c5f677561726469616e5f64756e67656f6e731802200328" .
            "0b32282e6d736767616d65646174612e4d7367467269656e6444756e6765" .
            "6f6e46696e64486973746f727942130a11636f6d2e66656c616e69612e6d" .
            "736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

