<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgSupportMonsterHistory.proto

namespace GPBMetadata;

class MsgSupportMonsterHistory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa9010a1e4d7367537570706f72744d6f6e73746572486973746f72792e" .
            "70726f746f120b6d736767616d6564617461225d0a184d7367537570706f" .
            "72744d6f6e73746572486973746f7279121b0a13737570706f72745f6d6f" .
            "6e737465725f75696418012003280712240a1c737570706f72745f6d6f6e" .
            "737465725f657870697265645f6461746518022003280442130a11636f6d" .
            "2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

