<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgStartMonster.proto

namespace GPBMetadata;

class MsgStartMonster
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8b010a154d736753746172744d6f6e737465722e70726f746f120b6d73" .
            "6767616d656461746122480a0f4d736753746172744d6f6e73746572120b" .
            "0a0375696418012001280712130a0b6d6f6e737465725f75696418022001" .
            "280712130a0b73746172745f6c6576656c18032001280742130a11636f6d" .
            "2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

