<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgShopItemMetaUserShipBuff.proto

namespace GPBMetadata;

class MsgShopItemMetaUserShipBuff
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a010a214d736753686f704974656d4d65746155736572536869704275" .
            "66662e70726f746f120b6d736767616d6564617461223b0a1b4d73675368" .
            "6f704974656d4d657461557365725368697042756666120c0a0473656c66" .
            "18012001280d120e0a06616c6c69657318022001280d42130a11636f6d2e" .
            "66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

