<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgSubStageEffect.proto

namespace GPBMetadata;

class MsgSubStageEffect
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af0010a174d736753756253746167654566666563742e70726f746f120b" .
            "6d736767616d656461746122aa010a114d73675375625374616765456666" .
            "65637412350a047479706518012001280e32272e6d736767616d65646174" .
            "612e4d736753756253746167654566666563742e44617461547970651215" .
            "0a0d696e635f676f6c645f70726f6218022001280212150a0d696e635f64" .
            "726f705f70726f6218032001280222300a08446174615479706512100a0c" .
            "44617461547970654e554c4c100012080a04476f6c64100112080a044472" .
            "6f70100242130a11636f6d2e66656c616e69612e6d736c6462620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

