<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUidAndAmount.proto

namespace GPBMetadata;

class MsgUidAndAmount
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a710a154d7367556964416e64416d6f756e742e70726f746f120b6d7367" .
            "67616d6564617461222e0a0f4d7367556964416e64416d6f756e74120b0a" .
            "03756964180120012807120e0a06616d6f756e7418022001280d42130a11" .
            "636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

