<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserClanMonsterSlotList.proto

namespace GPBMetadata;

class MsgUserClanMonsterSlotList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUserClanMonsterSlot::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acd010a204d736755736572436c616e4d6f6e73746572536c6f744c6973" .
            "742e70726f746f120b6d736767616d6564617461227f0a1a4d7367557365" .
            "72436c616e4d6f6e73746572536c6f744c697374120e0a06696e64696365" .
            "18012003280d123a0a0d6d6f6e737465725f736c6f747318022003280b32" .
            "232e6d736767616d65646174612e4d736755736572436c616e4d6f6e7374" .
            "6572536c6f7412150a0d757365645f6d6f6e737465727318032003280442" .
            "130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

