<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserLobbyReward.proto

namespace GPBMetadata;

class MsgUserLobbyReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad010a184d7367557365724c6f6262795265776172642e70726f746f12" .
            "0b6d736767616d656461746122670a124d7367557365724c6f6262795265" .
            "77617264120f0a07757365725f696418012001280412180a106c6f626279" .
            "5f7265776172645f75696418022001280d12110a09746f7563685f636e74" .
            "18032001280d12130a0b7570646174655f6461746518042001280442130a" .
            "11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

