<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserShopMeta.proto

namespace GPBMetadata;

class MsgUserShopMeta
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a740a154d73675573657253686f704d6574612e70726f746f120b6d7367" .
            "67616d656461746122310a0f4d73675573657253686f704d65746112100a" .
            "086974656d5f756964180120012807120c0a046d65746118022001280942" .
            "130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

