<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserCVCMonsterSlotList.proto

namespace GPBMetadata;

class MsgUserCVCMonsterSlotList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUserCVCMonsterSlot::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aba010a1f4d7367557365724356434d6f6e73746572536c6f744c697374" .
            "2e70726f746f120b6d736767616d6564617461226d0a194d736755736572" .
            "4356434d6f6e73746572536c6f744c69737412390a0d6d6f6e737465725f" .
            "736c6f747318012003280b32222e6d736767616d65646174612e4d736755" .
            "7365724356434d6f6e73746572536c6f7412150a0d757365645f6d6f6e73" .
            "7465727318022003280442130a11636f6d2e66656c616e69612e6d736c64" .
            "62620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

