<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserMeta.proto

namespace GPBMetadata;

class MsgUserMeta
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UserMetaType::initOnce();
        \GPBMetadata\UserMetaValueType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaa020a114d7367557365724d6574612e70726f746f120b6d736767616d" .
            "65646174611a17557365724d65746156616c7565547970652e70726f746f" .
            "22d1010a0b4d7367557365724d65746112270a047479706518012001280e" .
            "32192e6d736767616d65646174612e557365724d6574615479706512320a" .
            "0a76616c75655f7479706518022001280e321e2e6d736767616d65646174" .
            "612e557365724d65746156616c756554797065120e0a06765f626f6f6c18" .
            "0320012808120f0a07765f666c6f6174180420012802120d0a05765f696e" .
            "7418052001280d120e0a06765f6a736f6e18062001280912100a08765f73" .
            "7472696e6718072001280912130a0b6372656174655f6461746518082001" .
            "280442130a11636f6d2e66656c616e69612e6d736c6462620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

