<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserBingoEventData.proto

namespace GPBMetadata;

class MsgUserBingoEventData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3020a1b4d73675573657242696e676f4576656e74446174612e70726f" .
            "746f120b6d736767616d656461746122d9010a154d73675573657242696e" .
            "676f4576656e7444617461120f0a07757365725f69641801200128041216" .
            "0a0e62696e676f5f6576656e745f696418022001280412200a1862696e67" .
            "6f5f636f6d706c6574655f6576656e745f756964180320012804120d0a05" .
            "7469746c6518042001280912180a1073746172745f6c6f63616c5f646174" .
            "6518052001280412160a0e656e645f6c6f63616c5f646174651806200128" .
            "04121c0a14636f6d706c6574655f62696e676f5f636f756e741807200128" .
            "0d12160a0e72657761726461626c655f69647818082001280d42130a1163" .
            "6f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

