<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserBingoData.proto

namespace GPBMetadata;

class MsgUserBingoData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af1010a164d73675573657242696e676f446174612e70726f746f120b6d" .
            "736767616d656461746122ac010a104d73675573657242696e676f446174" .
            "61120f0a07757365725f696418012001280412180a1062696e676f5f7365" .
            "61736f6e5f75696418022001280712110a0962696e676f5f736574180320" .
            "01280d12130a0b62696e676f5f706861736518042001280d12130a0b6269" .
            "6e676f5f737461746518052001280d12170a0f6c6173745f6c6f67696e5f" .
            "74696d6518062001280412170a0f69735f62696e676f5f6368616e676518" .
            "072001280842130a11636f6d2e66656c616e69612e6d736c646262067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

