<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PackageItemState.proto

namespace GPBMetadata;

class PackageItemState
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84010a165061636b6167654974656d53746174652e70726f746f120b6d" .
            "736767616d65646174612a400a105061636b6167654974656d5374617465" .
            "12130a0f5049535f5075726368617361626c65100012170a135049535f41" .
            "6c72656164795075726368617365100142130a11636f6d2e66656c616e69" .
            "612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

