<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtocolVersion.proto

namespace GPBMetadata;

class ProtocolVersion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade010a1550726f746f636f6c56657273696f6e2e70726f746f120b6d73" .
            "6767616d65646174612a9a010a0f50726f746f636f6c56657273696f6e12" .
            "0d0a09565f556e6b6e6f776e1000120c0a08565f3039313831321027120c" .
            "0a08565f303931383139102812120a0e565f315f305f3137303330393031" .
            "102912120a0e565f315f305f3137303832343031102a12120a0e565f315f" .
            "305f3137303930373031102b12120a0e565f315f305f3137303932313031" .
            "102c120c0a08565f4c4154455354102d42130a11636f6d2e66656c616e69" .
            "612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

