<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RefreshArenaCandidatesType.proto

namespace GPBMetadata;

class RefreshArenaCandidatesType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5010a20526566726573684172656e6143616e64696461746573547970" .
            "652e70726f746f120b6d736767616d65646174612a770a1a526566726573" .
            "684172656e6143616e6469646174657354797065120a0a0652545f476574" .
            "100012180a1452545f467265655075626c697368427954696d651001121c" .
            "0a1852545f467265655075626c6973684279416c6c436c65617210021215" .
            "0a1152545f4e6f74467265655075626c697368100342130a11636f6d2e66" .
            "656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

