<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqArenaAttackBattleHistories.proto

namespace GPBMetadata;

class ReqArenaAttackBattleHistories
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a700a235265714172656e6141747461636b426174746c65486973746f72" .
            "6965732e70726f746f120b6d736767616d6564617461221f0a1d52657141" .
            "72656e6141747461636b426174746c65486973746f7269657342130a1163" .
            "6f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

