<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqArenaBattleHistories.proto

namespace GPBMetadata;

class ReqArenaBattleHistories
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a1d5265714172656e61426174746c65486973746f726965732e7072" .
            "6f746f120b6d736767616d656461746122190a175265714172656e614261" .
            "74746c65486973746f7269657342130a11636f6d2e66656c616e69612e6d" .
            "736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

