<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqClanApplyList.proto

namespace GPBMetadata;

class ReqClanApplyList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a670a16526571436c616e4170706c794c6973742e70726f746f120b6d73" .
            "6767616d656461746122230a10526571436c616e4170706c794c69737412" .
            "0f0a07636c616e5f696418012001280442130a11636f6d2e66656c616e69" .
            "612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

