<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqDestroyClan.proto

namespace GPBMetadata;

class ReqDestroyClan
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a520a1452657144657374726f79436c616e2e70726f746f120b6d736767" .
            "616d656461746122100a0e52657144657374726f79436c616e42130a1163" .
            "6f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

