<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqGetCaptureFestivalEventMessages.proto

namespace GPBMetadata;

class ReqGetCaptureFestivalEventMessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7a0a2852657147657443617074757265466573746976616c4576656e74" .
            "4d657373616765732e70726f746f120b6d736767616d656461746122240a" .
            "2252657147657443617074757265466573746976616c4576656e744d6573" .
            "736167657342130a11636f6d2e66656c616e69612e6d736c646262067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

