<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqGetRejoinClanReward.proto

namespace GPBMetadata;

class ReqGetRejoinClanReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a620a1c52657147657452656a6f696e436c616e5265776172642e70726f" .
            "746f120b6d736767616d656461746122180a1652657147657452656a6f69" .
            "6e436c616e52657761726442130a11636f6d2e66656c616e69612e6d736c" .
            "6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

