<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqGetClanSeasonHistory.proto

namespace GPBMetadata;

class ReqGetClanSeasonHistory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a1d526571476574436c616e536561736f6e486973746f72792e7072" .
            "6f746f120b6d736767616d656461746122190a17526571476574436c616e" .
            "536561736f6e486973746f727942130a11636f6d2e66656c616e69612e6d" .
            "736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

