<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqGetUserMeta.proto

namespace GPBMetadata;

class ReqGetUserMeta
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\UserMetaType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80010a14526571476574557365724d6574612e70726f746f120b6d7367" .
            "67616d6564617461223e0a0e526571476574557365724d657461122c0a09" .
            "6d6574615f7479706518012001280e32192e6d736767616d65646174612e" .
            "557365724d6574615479706542130a11636f6d2e66656c616e69612e6d73" .
            "6c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

