<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqMonsterSummonByEgg.proto

namespace GPBMetadata;

class ReqMonsterSummonByEgg
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8b010a1b5265714d6f6e7374657253756d6d6f6e42794567672e70726f" .
            "746f120b6d736767616d656461746122420a155265714d6f6e7374657253" .
            "756d6d6f6e427945676712100a086974656d5f7569641801200128071217" .
            "0a0f6d756c7469706c655f73756d6d6f6e18022001280842130a11636f6d" .
            "2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

