<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqPurchaseId.proto

namespace GPBMetadata;

class ReqPurchaseId
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a670a13526571507572636861736549642e70726f746f120b6d73676761" .
            "6d656461746122260a0d5265715075726368617365496412150a0d73686f" .
            "705f6974656d5f75696418012001280742130a11636f6d2e66656c616e69" .
            "612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

