<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqQuestClientEvent.proto

namespace GPBMetadata;

class ReqQuestClientEvent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgQuest::initOnce();
        \GPBMetadata\MsgNPCTalkTopic::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae2010a195265715175657374436c69656e744576656e742e70726f746f" .
            "120b6d736767616d65646174611a154d73674e504354616c6b546f706963" .
            "2e70726f746f2283010a135265715175657374436c69656e744576656e74" .
            "12330a0a6d61696e5f636f6e646918012001280e321f2e6d736767616d65" .
            "646174612e4d736751756573742e4d61696e436f6e646912370a0b765f6e" .
            "70635f7363656e6518022001280e32222e6d736767616d65646174612e4d" .
            "73674e504354616c6b546f7069632e5363656e6542130a11636f6d2e6665" .
            "6c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

