<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqReceiveUserGift.proto

namespace GPBMetadata;

class ReqReceiveUserGift
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6b0a185265715265636569766555736572476966742e70726f746f120b" .
            "6d736767616d656461746122250a12526571526563656976655573657247" .
            "696674120f0a07676966745f696418012001280442130a11636f6d2e6665" .
            "6c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

