<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSendCaptureFestivalEventMessage.proto

namespace GPBMetadata;

class ReqSendCaptureFestivalEventMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgCaptureFestivalEventMessage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe010a2852657153656e6443617074757265466573746976616c457665" .
            "6e744d6573736167652e70726f746f120b6d736767616d65646174612268" .
            "0a2252657153656e6443617074757265466573746976616c4576656e744d" .
            "65737361676512420a0d6576656e745f6d65737361676518012001280b32" .
            "2b2e6d736767616d65646174612e4d736743617074757265466573746976" .
            "616c4576656e744d65737361676542130a11636f6d2e66656c616e69612e" .
            "6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

