<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSelectStageSceneFooter.proto

namespace GPBMetadata;

class ReqSelectStageSceneFooter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\RefreshDungeonType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f010a1f52657153656c65637453746167655363656e65466f6f746572" .
            "2e70726f746f120b6d736767616d656461746122520a1952657153656c65" .
            "637453746167655363656e65466f6f74657212350a0c64756e67656f6e5f" .
            "7479706518012001280e321f2e6d736767616d65646174612e5265667265" .
            "736844756e67656f6e5479706542130a11636f6d2e66656c616e69612e6d" .
            "736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

