<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUserLogin.proto

namespace GPBMetadata;

class ReqUserLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\AccountPlatformType::initOnce();
        \GPBMetadata\MsgClientDeviceInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e020a12526571557365724c6f67696e2e70726f746f120b6d73676761" .
            "6d65646174611a194d7367436c69656e74446576696365496e666f2e7072" .
            "6f746f22c2010a0c526571557365724c6f67696e120c0a04757569641801" .
            "2001280912130a0b707269766174655f6b657918022001280912370a0d70" .
            "6c6174666f726d5f7479706518032001280e32202e6d736767616d656461" .
            "74612e4163636f756e74506c6174666f726d5479706512180a10706c6174" .
            "666f726d5f757365725f6964180420012809123c0a12636c69656e745f64" .
            "65766963655f696e666f18052001280b32202e6d736767616d6564617461" .
            "2e4d7367436c69656e74446576696365496e666f42130a11636f6d2e6665" .
            "6c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

