<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUserApplyList.proto

namespace GPBMetadata;

class ReqUserApplyList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a560a16526571557365724170706c794c6973742e70726f746f120b6d73" .
            "6767616d656461746122120a10526571557365724170706c794c69737442" .
            "130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

