<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUserBingoData.proto

namespace GPBMetadata;

class ReqUserBingoData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a560a165265715573657242696e676f446174612e70726f746f120b6d73" .
            "6767616d656461746122120a105265715573657242696e676f4461746142" .
            "130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

