<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUserBingoReward.proto

namespace GPBMetadata;

class ReqUserBingoReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUserBingoData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3010a185265715573657242696e676f5265776172642e70726f746f12" .
            "0b6d736767616d6564617461225d0a125265715573657242696e676f5265" .
            "7761726412360a0f757365725f62696e676f5f6461746118012001280b32" .
            "1d2e6d736767616d65646174612e4d73675573657242696e676f44617461" .
            "120f0a07656c617073656418022001280242130a11636f6d2e66656c616e" .
            "69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

