<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqVoteBoard.proto

namespace GPBMetadata;

class ReqVoteBoard
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a620a12526571566f7465426f6172642e70726f746f120b6d736767616d" .
            "656461746122220a0c526571566f7465426f61726412120a0a6d65737361" .
            "67655f696418012001280442130a11636f6d2e66656c616e69612e6d736c" .
            "6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

