<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspCancelUserApply.proto

namespace GPBMetadata;

class RspCancelUserApply
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6b0a1852737043616e63656c557365724170706c792e70726f746f120b" .
            "6d736767616d656461746122250a1252737043616e63656c557365724170" .
            "706c79120f0a07636c616e5f696418012001280442130a11636f6d2e6665" .
            "6c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

