<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspCVCCandidateList.proto

namespace GPBMetadata;

class RspCVCCandidateList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgCVCCandidateMember::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f010a1952737043564343616e6469646174654c6973742e70726f746f" .
            "120b6d736767616d656461746122580a1352737043564343616e64696461" .
            "74654c69737412410a1563616e6469646174655f6d656d6265725f6c6973" .
            "7418012003280b32222e6d736767616d65646174612e4d73674356434361" .
            "6e6469646174654d656d62657242130a11636f6d2e66656c616e69612e6d" .
            "736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

