<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspDailyBonusList.proto

namespace GPBMetadata;

class RspDailyBonusList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgCheckDailyBonus::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93010a175273704461696c79426f6e75734c6973742e70726f746f120b" .
            "6d736767616d6564617461224e0a115273704461696c79426f6e75734c69" .
            "737412390a106461696c795f626f6e75735f6c69737418012003280b321f" .
            "2e6d736767616d65646174612e4d7367436865636b4461696c79426f6e75" .
            "7342130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

