<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspExtendMonsterInven.proto

namespace GPBMetadata;

class RspExtendMonsterInven
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUser::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84010a1b527370457874656e644d6f6e73746572496e76656e2e70726f" .
            "746f120b6d736767616d6564617461223b0a15527370457874656e644d6f" .
            "6e73746572496e76656e12220a047573657218012001280b32142e6d7367" .
            "67616d65646174612e4d73675573657242130a11636f6d2e66656c616e69" .
            "612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

