<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspFinalMonsterEvolution.proto

namespace GPBMetadata;

class RspFinalMonsterEvolution
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUser::initOnce();
        \GPBMetadata\MsgUserMonster::initOnce();
        \GPBMetadata\MsgUserMonsterDictData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8020a1e52737046696e616c4d6f6e7374657245766f6c7574696f6e2e" .
            "70726f746f120b6d736767616d65646174611a144d7367557365724d6f6e" .
            "737465722e70726f746f1a1c4d7367557365724d6f6e7374657244696374" .
            "446174612e70726f746f22f7010a1852737046696e616c4d6f6e73746572" .
            "45766f6c7574696f6e121c0a14626173655f757365725f6d6f6e73746572" .
            "5f696418012001280412220a047573657218022001280b32142e6d736767" .
            "616d65646174612e4d73675573657212310a0c757365725f6d6f6e737465" .
            "7218032001280b321b2e6d736767616d65646174612e4d7367557365724d" .
            "6f6e7374657212430a16757365725f6d6f6e737465725f646963745f6461" .
            "746118042001280b32232e6d736767616d65646174612e4d736755736572" .
            "4d6f6e73746572446963744461746112210a196d6174657269616c5f7573" .
            "65725f6d6f6e737465725f69647318052003280442130a11636f6d2e6665" .
            "6c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

