<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspPushSetting.proto

namespace GPBMetadata;

class RspPushSetting
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\AccountPushSetting::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb010a145273705075736853657474696e672e70726f746f120b6d7367" .
            "67616d656461746122790a0e5273705075736853657474696e6712330a0a" .
            "707573685f616c61726d18012001280e321f2e6d736767616d6564617461" .
            "2e4163636f756e745075736853657474696e6712320a09736d735f616c61" .
            "726d18022001280e321f2e6d736767616d65646174612e4163636f756e74" .
            "5075736853657474696e6742130a11636f6d2e66656c616e69612e6d736c" .
            "6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

