<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspPromisePackageCheck.proto

namespace GPBMetadata;

class RspPromisePackageCheck
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUserShopMeta::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf010a1c52737050726f6d6973655061636b616765436865636b2e7072" .
            "6f746f120b6d736767616d656461746122650a1652737050726f6d697365" .
            "5061636b616765436865636b12150a0d73686f705f6974656d5f75696418" .
            "012001280712340a0e757365725f73686f705f6d65746118022001280b32" .
            "1c2e6d736767616d65646174612e4d73675573657253686f704d65746142" .
            "130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

