<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspQuestUpdate.proto

namespace GPBMetadata;

class RspQuestUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUserQuest::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7d0a1452737051756573745570646174652e70726f746f120b6d736767" .
            "616d6564617461223b0a0e527370517565737455706461746512290a0671" .
            "756573747318012003280b32192e6d736767616d65646174612e4d736755" .
            "736572517565737442130a11636f6d2e66656c616e69612e6d736c646262" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

