<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSelectStageSceneFooter.proto

namespace GPBMetadata;

class RspSelectStageSceneFooter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\RefreshDungeonType::initOnce();
        \GPBMetadata\MsgClanListData::initOnce();
        \GPBMetadata\MsgUserCVCMember::initOnce();
        \GPBMetadata\MsgSpecialGuardianDungeonData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac7030a1f52737053656c65637453746167655363656e65466f6f746572" .
            "2e70726f746f120b6d736767616d65646174611a154d7367436c616e4c69" .
            "7374446174612e70726f746f1a164d7367557365724356434d656d626572" .
            "2e70726f746f1a234d73675370656369616c477561726469616e44756e67" .
            "656f6e446174612e70726f746f22a5020a1952737053656c656374537461" .
            "67655363656e65466f6f746572120d0a05636f756e7418012001280d1235" .
            "0a0c64756e67656f6e5f7479706518022001280e321f2e6d736767616d65" .
            "646174612e5265667265736844756e67656f6e5479706512340a0e636c61" .
            "6e5f6c6973745f6461746118032003280b321c2e6d736767616d65646174" .
            "612e4d7367436c616e4c6973744461746112390a126d795f636c616e5f63" .
            "76635f6d656d62657218042001280b321d2e6d736767616d65646174612e" .
            "4d7367557365724356434d656d62657212510a1d7370656369616c5f6775" .
            "61726469616e5f64756e67656f6e5f6461746118052001280b322a2e6d73" .
            "6767616d65646174612e4d73675370656369616c477561726469616e4475" .
            "6e67656f6e4461746142130a11636f6d2e66656c616e69612e6d736c6462" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

