<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSendGiftToFriend.proto

namespace GPBMetadata;

class RspSendGiftToFriend
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUser::initOnce();
        \GPBMetadata\MsgPrice::initOnce();
        \GPBMetadata\MsgFriend::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89020a1952737053656e6447696674546f467269656e642e70726f746f" .
            "120b6d736767616d65646174611a0e4d736750726963652e70726f746f1a" .
            "0f4d7367467269656e642e70726f746f22a0010a1352737053656e644769" .
            "6674546f467269656e6412160a0e667269656e645f757365725f69641801" .
            "2001280412220a047573657218022001280b32142e6d736767616d656461" .
            "74612e4d73675573657212250a0672657761726418032001280b32152e6d" .
            "736767616d65646174612e4d7367507269636512260a06667269656e6418" .
            "042001280b32162e6d736767616d65646174612e4d7367467269656e6442" .
            "130a11636f6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

