<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspUserBingoReward.proto

namespace GPBMetadata;

class RspUserBingoReward
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgUserBingoData::initOnce();
        \GPBMetadata\MsgUserGift::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aef010a185273705573657242696e676f5265776172642e70726f746f12" .
            "0b6d736767616d65646174611a114d736755736572476966742e70726f74" .
            "6f2295010a125273705573657242696e676f52657761726412360a0f7573" .
            "65725f62696e676f5f6461746118012001280b321d2e6d736767616d6564" .
            "6174612e4d73675573657242696e676f44617461121c0a14757365725f6e" .
            "65775f62696e676f5f706965636518022001280d12290a07726577617264" .
            "7318032003280b32182e6d736767616d65646174612e4d73675573657247" .
            "69667442130a11636f6d2e66656c616e69612e6d736c6462620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

