<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspUserLevelUp.proto

namespace GPBMetadata;

class RspUserLevelUp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a790a14527370557365724c6576656c55702e70726f746f120b6d736767" .
            "616d656461746122370a0e527370557365724c6576656c5570120b0a036c" .
            "657618012001280d12180a106c657675705f7265776172645f67656d1802" .
            "2001280d42130a11636f6d2e66656c616e69612e6d736c6462620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

