<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspVoteRecommendMonsterParty.proto

namespace GPBMetadata;

class RspVoteRecommendMonsterParty
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MsgRecommendMonsterParty::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6010a22527370566f74655265636f6d6d656e644d6f6e737465725061" .
            "7274792e70726f746f120b6d736767616d656461746122660a1c52737056" .
            "6f74655265636f6d6d656e644d6f6e73746572506172747912460a177265" .
            "636f6d6d656e645f6d6f6e737465725f706172747918012001280b32252e" .
            "6d736767616d65646174612e4d73675265636f6d6d656e644d6f6e737465" .
            "72506172747942130a11636f6d2e66656c616e69612e6d736c6462620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

