<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileIconUnlockType.proto

namespace GPBMetadata;

class UserProfileIconUnlockType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9b010a1f5573657250726f66696c6549636f6e556e6c6f636b54797065" .
            "2e70726f746f120b6d736767616d65646174612a4e0a195573657250726f" .
            "66696c6549636f6e556e6c6f636b5479706512100a0c555049555f446566" .
            "61756c74100012100a0c555049555f4275794974656d1001120d0a095550" .
            "49555f4c696b65100242130a11636f6d2e66656c616e69612e6d736c6462" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

