<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserAccountSanctionType.proto

namespace GPBMetadata;

class UserAccountSanctionType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84020a1d557365724163636f756e7453616e6374696f6e547970652e70" .
            "726f746f120b6d736767616d65646174612ab8010a17557365724163636f" .
            "756e7453616e6374696f6e54797065120d0a09554153545f4e6f6e651000" .
            "12150a11554153545f54656d706f7261727942616e100112170a13554153" .
            "545f506f6c69637956696f6c656e63651002121a0a16554153545f41626e" .
            "6f726d616c53797374656d557365100312190a15554153545f41626e6f72" .
            "6d616c5075726368617365100412110a0d554153545f4162757365427567" .
            "100512140a10554153545f4261644e69636b6e616d65100642130a11636f" .
            "6d2e66656c616e69612e6d736c6462620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

