<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AccountPlatformType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\AccountPlatformType</code>
 */
class AccountPlatformType
{
    /**
     * Generated from protobuf enum <code>AccountPlatformTypeNULL = 0;</code>
     */
    const AccountPlatformTypeNULL = 0;
    /**
     * Generated from protobuf enum <code>APT_None = 3;</code>
     */
    const APT_None = 3;
    /**
     * Generated from protobuf enum <code>APT_Facebook = 4;</code>
     */
    const APT_Facebook = 4;
    /**
     * Generated from protobuf enum <code>APT_Guest = 5;</code>
     */
    const APT_Guest = 5;
    /**
     * Generated from protobuf enum <code>APT_GameCenter = 6;</code>
     */
    const APT_GameCenter = 6;
    /**
     * Generated from protobuf enum <code>APT_Google = 7;</code>
     */
    const APT_Google = 7;
    /**
     * Generated from protobuf enum <code>APT_QQ = 11;</code>
     */
    const APT_QQ = 11;
    /**
     * Generated from protobuf enum <code>APT_WeChat = 12;</code>
     */
    const APT_WeChat = 12;
    /**
     * Generated from protobuf enum <code>APT_ZplayUser = 13;</code>
     */
    const APT_ZplayUser = 13;
}

