<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AdminNoticeType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\AdminNoticeType</code>
 */
class AdminNoticeType
{
    /**
     * Generated from protobuf enum <code>ANT_Notice = 0;</code>
     */
    const ANT_Notice = 0;
    /**
     * Generated from protobuf enum <code>ANT_Gift = 1;</code>
     */
    const ANT_Gift = 1;
    /**
     * Generated from protobuf enum <code>ANT_GmDungeon = 2;</code>
     */
    const ANT_GmDungeon = 2;
    /**
     * Generated from protobuf enum <code>ANT_ServerEvent = 3;</code>
     */
    const ANT_ServerEvent = 3;
}

