<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CaptureFestivalLuckyTicketChangeCause.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\CaptureFestivalLuckyTicketChangeCause</code>
 */
class CaptureFestivalLuckyTicketChangeCause
{
    /**
     * Generated from protobuf enum <code>CaptureFestivalLuckyTicketChangeCauseNULL = 0;</code>
     */
    const CaptureFestivalLuckyTicketChangeCauseNULL = 0;
    /**
     * Generated from protobuf enum <code>CFLTCC_Get_Share_Reward = 1;</code>
     */
    const CFLTCC_Get_Share_Reward = 1;
    /**
     * Generated from protobuf enum <code>CFLTCC_Get_Send_Message_Reward = 2;</code>
     */
    const CFLTCC_Get_Send_Message_Reward = 2;
    /**
     * Generated from protobuf enum <code>CFLTCC_Get_Capture_Success_Reward = 3;</code>
     */
    const CFLTCC_Get_Capture_Success_Reward = 3;
    /**
     * Generated from protobuf enum <code>CFLTCC_Get_Top_Rank_Reward = 4;</code>
     */
    const CFLTCC_Get_Top_Rank_Reward = 4;
    /**
     * Generated from protobuf enum <code>CFLTCC_Get_Bonus_Ticket = 5;</code>
     */
    const CFLTCC_Get_Bonus_Ticket = 5;
    /**
     * Generated from protobuf enum <code>CFLTCC_Use_Finale_Reward = 10;</code>
     */
    const CFLTCC_Use_Finale_Reward = 10;
}

