<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClanPointChangeCause.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\ClanPointChangeCause</code>
 */
class ClanPointChangeCause
{
    /**
     * Generated from protobuf enum <code>ClanPointChangeCauseNULL = 0;</code>
     */
    const ClanPointChangeCauseNULL = 0;
    /**
     * Generated from protobuf enum <code>CPCC_Get_Clan_Battle_Clear_Reward = 1;</code>
     */
    const CPCC_Get_Clan_Battle_Clear_Reward = 1;
    /**
     * Generated from protobuf enum <code>CPCC_Get_Clan_Battle_Season_Reward = 2;</code>
     */
    const CPCC_Get_Clan_Battle_Season_Reward = 2;
    /**
     * Generated from protobuf enum <code>CPCC_Get_Clan_Attendance_Reward = 3;</code>
     */
    const CPCC_Get_Clan_Attendance_Reward = 3;
    /**
     * Generated from protobuf enum <code>CPCC_Get_CVC_Battle_Reward = 4;</code>
     */
    const CPCC_Get_CVC_Battle_Reward = 4;
    /**
     * Generated from protobuf enum <code>CPCC_Get_CVC_Season_Reward = 5;</code>
     */
    const CPCC_Get_CVC_Season_Reward = 5;
    /**
     * Generated from protobuf enum <code>CPCC_Use_Buy_Shop = 50;</code>
     */
    const CPCC_Use_Buy_Shop = 50;
}

