<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendState.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\FriendState</code>
 */
class FriendState
{
    /**
     * Generated from protobuf enum <code>FS_Requested = 0;</code>
     */
    const FS_Requested = 0;
    /**
     * Generated from protobuf enum <code>FS_MakeFriend = 1;</code>
     */
    const FS_MakeFriend = 1;
    /**
     * Generated from protobuf enum <code>FS_WaitToResponse = 2;</code>
     */
    const FS_WaitToResponse = 2;
}

