<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GlobalDataType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\GlobalDataType</code>
 */
class GlobalDataType
{
    /**
     * Generated from protobuf enum <code>GDT_None = 0;</code>
     */
    const GDT_None = 0;
    /**
     * Generated from protobuf enum <code>GDT_FreeGem = 1;</code>
     */
    const GDT_FreeGem = 1;
    /**
     * Generated from protobuf enum <code>GDT_PaidGem = 2;</code>
     */
    const GDT_PaidGem = 2;
    /**
     * Generated from protobuf enum <code>GDT_Gold = 3;</code>
     */
    const GDT_Gold = 3;
    /**
     * Generated from protobuf enum <code>GDT_Energy = 4;</code>
     */
    const GDT_Energy = 4;
    /**
     * Generated from protobuf enum <code>GDT_DungeonTicket = 5;</code>
     */
    const GDT_DungeonTicket = 5;
    /**
     * Generated from protobuf enum <code>GDT_ArenaTicket = 6;</code>
     */
    const GDT_ArenaTicket = 6;
    /**
     * Generated from protobuf enum <code>GDT_ArenaPoint = 7;</code>
     */
    const GDT_ArenaPoint = 7;
    /**
     * Generated from protobuf enum <code>GDT_Exp = 8;</code>
     */
    const GDT_Exp = 8;
    /**
     * Generated from protobuf enum <code>GDT_SoulStone = 100;</code>
     */
    const GDT_SoulStone = 100;
    /**
     * Generated from protobuf enum <code>GDT_Rune = 101;</code>
     */
    const GDT_Rune = 101;
    /**
     * Generated from protobuf enum <code>GDT_Monster = 102;</code>
     */
    const GDT_Monster = 102;
    /**
     * Generated from protobuf enum <code>GDT_MonsterPackage = 103;</code>
     */
    const GDT_MonsterPackage = 103;
    /**
     * Generated from protobuf enum <code>GDT_Food = 104;</code>
     */
    const GDT_Food = 104;
    /**
     * Generated from protobuf enum <code>GDT_BeyondStone = 105;</code>
     */
    const GDT_BeyondStone = 105;
    /**
     * Generated from protobuf enum <code>GDT_MonsterEgg = 106;</code>
     */
    const GDT_MonsterEgg = 106;
    /**
     * Generated from protobuf enum <code>GDT_StarEssence = 107;</code>
     */
    const GDT_StarEssence = 107;
    /**
     * Generated from protobuf enum <code>GDT_Random = 108;</code>
     */
    const GDT_Random = 108;
    /**
     * Generated from protobuf enum <code>GDT_MonsterSkillBook = 109;</code>
     */
    const GDT_MonsterSkillBook = 109;
    /**
     * Generated from protobuf enum <code>GDT_SuperStone = 110;</code>
     */
    const GDT_SuperStone = 110;
    /**
     * Generated from protobuf enum <code>GDT_SuperStoneStuff = 111;</code>
     */
    const GDT_SuperStoneStuff = 111;
    /**
     * Generated from protobuf enum <code>GDT_MpCrystal = 200;</code>
     */
    const GDT_MpCrystal = 200;
    /**
     * Generated from protobuf enum <code>GDT_HpCrystal = 201;</code>
     */
    const GDT_HpCrystal = 201;
    /**
     * Generated from protobuf enum <code>GDT_Gun = 202;</code>
     */
    const GDT_Gun = 202;
    /**
     * Generated from protobuf enum <code>GDT_Bullet = 203;</code>
     */
    const GDT_Bullet = 203;
    /**
     * Generated from protobuf enum <code>GDT_InstantGold = 204;</code>
     */
    const GDT_InstantGold = 204;
    /**
     * Generated from protobuf enum <code>GDT_ProfileIcon = 205;</code>
     */
    const GDT_ProfileIcon = 205;
    /**
     * Generated from protobuf enum <code>GDT_JojeShopRefresh = 206;</code>
     */
    const GDT_JojeShopRefresh = 206;
    /**
     * Generated from protobuf enum <code>GDT_BattleContinue = 207;</code>
     */
    const GDT_BattleContinue = 207;
    /**
     * Generated from protobuf enum <code>GDT_ExtendMonsterSlot = 208;</code>
     */
    const GDT_ExtendMonsterSlot = 208;
    /**
     * Generated from protobuf enum <code>GDT_Revive = 209;</code>
     */
    const GDT_Revive = 209;
    /**
     * Generated from protobuf enum <code>GDT_MonsterRelease = 210;</code>
     */
    const GDT_MonsterRelease = 210;
}

