<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LogCurrencyType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\LogCurrencyType</code>
 */
class LogCurrencyType
{
    /**
     * Generated from protobuf enum <code>LogCurrencyTypeNULL = 0;</code>
     */
    const LogCurrencyTypeNULL = 0;
    /**
     * Generated from protobuf enum <code>LCT_Gold = 1;</code>
     */
    const LCT_Gold = 1;
    /**
     * Generated from protobuf enum <code>LCT_Gem = 2;</code>
     */
    const LCT_Gem = 2;
    /**
     * Generated from protobuf enum <code>LCT_Energy = 3;</code>
     */
    const LCT_Energy = 3;
    /**
     * Generated from protobuf enum <code>LCT_Arena_Ticket = 4;</code>
     */
    const LCT_Arena_Ticket = 4;
    /**
     * Generated from protobuf enum <code>LCT_Arena_Point = 5;</code>
     */
    const LCT_Arena_Point = 5;
    /**
     * Generated from protobuf enum <code>LCT_Dungeon_Ticket = 6;</code>
     */
    const LCT_Dungeon_Ticket = 6;
}

