<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MonsterCostumeBundleChangeType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MonsterCostumeBundleChangeType</code>
 */
class MonsterCostumeBundleChangeType
{
    /**
     * Generated from protobuf enum <code>MonsterCostumeBundleChangeTypeNULL = 0;</code>
     */
    const MonsterCostumeBundleChangeTypeNULL = 0;
    /**
     * Generated from protobuf enum <code>MCBCT_Gain = 1;</code>
     */
    const MCBCT_Gain = 1;
}

