<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MonsterSkillTargetType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MonsterSkillTargetType</code>
 */
class MonsterSkillTargetType
{
    /**
     * Generated from protobuf enum <code>MonsterSkillTargetTypeNULL = 0;</code>
     */
    const MonsterSkillTargetTypeNULL = 0;
    /**
     * Generated from protobuf enum <code>MST_One = 1;</code>
     */
    const MST_One = 1;
    /**
     * Generated from protobuf enum <code>MST_All = 2;</code>
     */
    const MST_All = 2;
    /**
     * Generated from protobuf enum <code>MST_Team = 3;</code>
     */
    const MST_Team = 3;
    /**
     * Generated from protobuf enum <code>MST_EntireAll = 4;</code>
     */
    const MST_EntireAll = 4;
}

