<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgArenaGainWinningPoint.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgArenaGainWinningPoint</code>
 */
class MsgArenaGainWinningPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>uint32 win = 3;</code>
     */
    private $win = 0;
    /**
     * Generated from protobuf field <code>uint32 lose = 4;</code>
     */
    private $lose = 0;
    /**
     * Generated from protobuf field <code>uint32 draw = 5;</code>
     */
    private $draw = 0;
    /**
     * Generated from protobuf field <code>uint32 min = 6;</code>
     */
    private $min = 0;
    /**
     * Generated from protobuf field <code>uint32 max = 7;</code>
     */
    private $max = 0;

    public function __construct() {
        \GPBMetadata\MsgArenaGainWinningPoint::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 win = 3;</code>
     * @return int
     */
    public function getWin()
    {
        return $this->win;
    }

    /**
     * Generated from protobuf field <code>uint32 win = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setWin($var)
    {
        GPBUtil::checkUint32($var);
        $this->win = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 lose = 4;</code>
     * @return int
     */
    public function getLose()
    {
        return $this->lose;
    }

    /**
     * Generated from protobuf field <code>uint32 lose = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLose($var)
    {
        GPBUtil::checkUint32($var);
        $this->lose = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 draw = 5;</code>
     * @return int
     */
    public function getDraw()
    {
        return $this->draw;
    }

    /**
     * Generated from protobuf field <code>uint32 draw = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDraw($var)
    {
        GPBUtil::checkUint32($var);
        $this->draw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 min = 6;</code>
     * @return int
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * Generated from protobuf field <code>uint32 min = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMin($var)
    {
        GPBUtil::checkUint32($var);
        $this->min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max = 7;</code>
     * @return int
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * Generated from protobuf field <code>uint32 max = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkUint32($var);
        $this->max = $var;

        return $this;
    }

}

