<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgBattleEndClan.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgBattleEndClan</code>
 */
class MsgBattleEndClan extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 battle_id = 1;</code>
     */
    private $battle_id = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.BattleEndResultType result = 2;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>uint32 end_boss_lev = 3;</code>
     */
    private $end_boss_lev = 0;
    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp = 4;</code>
     */
    private $end_boss_dec_hp = 0;
    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp_by_hit = 5;</code>
     */
    private $end_boss_dec_hp_by_hit = 0;
    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp_by_status_effect = 6;</code>
     */
    private $end_boss_dec_hp_by_status_effect = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgBattleMonsterStat mon_result_data = 7;</code>
     */
    private $mon_result_data;

    public function __construct() {
        \GPBMetadata\MsgBattleEndClan::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 battle_id = 1;</code>
     * @return int|string
     */
    public function getBattleId()
    {
        return $this->battle_id;
    }

    /**
     * Generated from protobuf field <code>uint64 battle_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBattleId($var)
    {
        GPBUtil::checkUint64($var);
        $this->battle_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.BattleEndResultType result = 2;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.BattleEndResultType result = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\BattleEndResultType::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 end_boss_lev = 3;</code>
     * @return int
     */
    public function getEndBossLev()
    {
        return $this->end_boss_lev;
    }

    /**
     * Generated from protobuf field <code>uint32 end_boss_lev = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setEndBossLev($var)
    {
        GPBUtil::checkUint32($var);
        $this->end_boss_lev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp = 4;</code>
     * @return int|string
     */
    public function getEndBossDecHp()
    {
        return $this->end_boss_dec_hp;
    }

    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndBossDecHp($var)
    {
        GPBUtil::checkUint64($var);
        $this->end_boss_dec_hp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp_by_hit = 5;</code>
     * @return int|string
     */
    public function getEndBossDecHpByHit()
    {
        return $this->end_boss_dec_hp_by_hit;
    }

    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp_by_hit = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndBossDecHpByHit($var)
    {
        GPBUtil::checkUint64($var);
        $this->end_boss_dec_hp_by_hit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp_by_status_effect = 6;</code>
     * @return int|string
     */
    public function getEndBossDecHpByStatusEffect()
    {
        return $this->end_boss_dec_hp_by_status_effect;
    }

    /**
     * Generated from protobuf field <code>uint64 end_boss_dec_hp_by_status_effect = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndBossDecHpByStatusEffect($var)
    {
        GPBUtil::checkUint64($var);
        $this->end_boss_dec_hp_by_status_effect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgBattleMonsterStat mon_result_data = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMonResultData()
    {
        return $this->mon_result_data;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgBattleMonsterStat mon_result_data = 7;</code>
     * @param \Msggamedata\MsgBattleMonsterStat[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMonResultData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgBattleMonsterStat::class);
        $this->mon_result_data = $arr;

        return $this;
    }

}

