<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgBattleMasterScript.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MsgBattleMasterScript\MasterScriptType</code>
 */
class MsgBattleMasterScript_MasterScriptType
{
    /**
     * Generated from protobuf enum <code>None = 0;</code>
     */
    const None = 0;
    /**
     * Generated from protobuf enum <code>StartBattle = 1;</code>
     */
    const StartBattle = 1;
    /**
     * Generated from protobuf enum <code>EnterRound = 2;</code>
     */
    const EnterRound = 2;
    /**
     * Generated from protobuf enum <code>EnterBossRound = 3;</code>
     */
    const EnterBossRound = 3;
    /**
     * Generated from protobuf enum <code>RareMonsterDetected = 4;</code>
     */
    const RareMonsterDetected = 4;
    /**
     * Generated from protobuf enum <code>DoAttack = 5;</code>
     */
    const DoAttack = 5;
    /**
     * Generated from protobuf enum <code>GetCriticalDamage = 6;</code>
     */
    const GetCriticalDamage = 6;
    /**
     * Generated from protobuf enum <code>DeadMyMonster = 7;</code>
     */
    const DeadMyMonster = 7;
    /**
     * Generated from protobuf enum <code>SelectCaptureMonster = 8;</code>
     */
    const SelectCaptureMonster = 8;
    /**
     * Generated from protobuf enum <code>SucceedCapture = 9;</code>
     */
    const SucceedCapture = 9;
    /**
     * Generated from protobuf enum <code>FailedCapture = 10;</code>
     */
    const FailedCapture = 10;
}

