<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgCaptureFestivalTicketCondition.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgCaptureFestivalTicketCondition</code>
 */
class MsgCaptureFestivalTicketCondition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgCaptureFestivalTicketCondition.TicketConditionType type = 2;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgCaptureFestivalTicketCondition.TicketConditionActor actor = 3;</code>
     */
    private $actor = 0;
    /**
     * Generated from protobuf field <code>uint32 count = 4;</code>
     */
    private $count = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount reward = 5;</code>
     */
    private $reward = null;
    /**
     * Generated from protobuf field <code>fixed32 title = 6;</code>
     */
    private $title = 0;

    public function __construct() {
        \GPBMetadata\MsgCaptureFestivalTicketCondition::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgCaptureFestivalTicketCondition.TicketConditionType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgCaptureFestivalTicketCondition.TicketConditionType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgCaptureFestivalTicketCondition_TicketConditionType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgCaptureFestivalTicketCondition.TicketConditionActor actor = 3;</code>
     * @return int
     */
    public function getActor()
    {
        return $this->actor;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgCaptureFestivalTicketCondition.TicketConditionActor actor = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setActor($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgCaptureFestivalTicketCondition_TicketConditionActor::class);
        $this->actor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 4;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount reward = 5;</code>
     * @return \Msggamedata\MsgUidAndAmount
     */
    public function getReward()
    {
        return $this->reward;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount reward = 5;</code>
     * @param \Msggamedata\MsgUidAndAmount $var
     * @return $this
     */
    public function setReward($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUidAndAmount::class);
        $this->reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 title = 6;</code>
     * @return int
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>fixed32 title = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkUint32($var);
        $this->title = $var;

        return $this;
    }

}

