<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgContractorSeason.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgContractorSeason</code>
 */
class MsgContractorSeason extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgContractor contractors = 2;</code>
     */
    private $contractors;
    /**
     * Generated from protobuf field <code>string ext_img = 3;</code>
     */
    private $ext_img = '';

    public function __construct() {
        \GPBMetadata\MsgContractorSeason::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgContractor contractors = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContractors()
    {
        return $this->contractors;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgContractor contractors = 2;</code>
     * @param \Msggamedata\MsgContractor[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContractors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgContractor::class);
        $this->contractors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ext_img = 3;</code>
     * @return string
     */
    public function getExtImg()
    {
        return $this->ext_img;
    }

    /**
     * Generated from protobuf field <code>string ext_img = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setExtImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ext_img = $var;

        return $this;
    }

}

