<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgClanSeasonBattle.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgClanSeasonBattle</code>
 */
class MsgClanSeasonBattle extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgClanSeasonBattle.BattleDay battle_day = 2;</code>
     */
    private $battle_day = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime open_time = 3;</code>
     */
    private $open_time = null;
    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime close_time = 4;</code>
     */
    private $close_time = null;
    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime register_time = 5;</code>
     */
    private $register_time = null;

    public function __construct() {
        \GPBMetadata\MsgClanSeasonBattle::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgClanSeasonBattle.BattleDay battle_day = 2;</code>
     * @return int
     */
    public function getBattleDay()
    {
        return $this->battle_day;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgClanSeasonBattle.BattleDay battle_day = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBattleDay($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgClanSeasonBattle_BattleDay::class);
        $this->battle_day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime open_time = 3;</code>
     * @return \Msggamedata\ProtoTime
     */
    public function getOpenTime()
    {
        return $this->open_time;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime open_time = 3;</code>
     * @param \Msggamedata\ProtoTime $var
     * @return $this
     */
    public function setOpenTime($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\ProtoTime::class);
        $this->open_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime close_time = 4;</code>
     * @return \Msggamedata\ProtoTime
     */
    public function getCloseTime()
    {
        return $this->close_time;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime close_time = 4;</code>
     * @param \Msggamedata\ProtoTime $var
     * @return $this
     */
    public function setCloseTime($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\ProtoTime::class);
        $this->close_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime register_time = 5;</code>
     * @return \Msggamedata\ProtoTime
     */
    public function getRegisterTime()
    {
        return $this->register_time;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.ProtoTime register_time = 5;</code>
     * @param \Msggamedata\ProtoTime $var
     * @return $this
     */
    public function setRegisterTime($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\ProtoTime::class);
        $this->register_time = $var;

        return $this;
    }

}

