<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgClan.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgClan</code>
 */
class MsgClan extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 clan_id = 1;</code>
     */
    private $clan_id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>uint64 timezone = 3;</code>
     */
    private $timezone = 0;
    /**
     * Generated from protobuf field <code>uint32 lev = 4;</code>
     */
    private $lev = 0;
    /**
     * Generated from protobuf field <code>uint32 exp = 5;</code>
     */
    private $exp = 0;
    /**
     * Generated from protobuf field <code>uint32 emblem_id = 6;</code>
     */
    private $emblem_id = 0;
    /**
     * Generated from protobuf field <code>uint32 member_count = 7;</code>
     */
    private $member_count = 0;
    /**
     * Generated from protobuf field <code>uint32 max_member_count = 8;</code>
     */
    private $max_member_count = 0;
    /**
     * Generated from protobuf field <code>uint32 vice_master_count = 9;</code>
     */
    private $vice_master_count = 0;
    /**
     * Generated from protobuf field <code>uint32 join_season_count = 10;</code>
     */
    private $join_season_count = 0;
    /**
     * Generated from protobuf field <code>uint32 max_boss_lev = 11;</code>
     */
    private $max_boss_lev = 0;
    /**
     * Generated from protobuf field <code>uint32 best_cvc_rank = 12;</code>
     */
    private $best_cvc_rank = 0;
    /**
     * Generated from protobuf field <code>string chatting_notice = 13;</code>
     */
    private $chatting_notice = '';
    /**
     * Generated from protobuf field <code>string comment = 14;</code>
     */
    private $comment = '';
    /**
     * Generated from protobuf field <code>string clan_festival_message = 15;</code>
     */
    private $clan_festival_message = '';
    /**
     * Generated from protobuf field <code>string desc = 16;</code>
     */
    private $desc = '';
    /**
     * Generated from protobuf field <code>uint32 status = 17;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>uint64 req_date = 18;</code>
     */
    private $req_date = 0;
    /**
     * Generated from protobuf field <code>string private_key = 19;</code>
     */
    private $private_key = '';
    /**
     * Generated from protobuf field <code>string public_key = 20;</code>
     */
    private $public_key = '';
    /**
     * Generated from protobuf field <code>uint32 apprentice_count = 21;</code>
     */
    private $apprentice_count = 0;
    /**
     * Generated from protobuf field <code>uint32 attendance_count = 22;</code>
     */
    private $attendance_count = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.CVCSeasonState cvc_season_state = 23;</code>
     */
    private $cvc_season_state = 0;
    /**
     * Generated from protobuf field <code>uint32 cvc_battle_phase_count = 24;</code>
     */
    private $cvc_battle_phase_count = 0;

    public function __construct() {
        \GPBMetadata\MsgClan::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 clan_id = 1;</code>
     * @return int|string
     */
    public function getClanId()
    {
        return $this->clan_id;
    }

    /**
     * Generated from protobuf field <code>uint64 clan_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClanId($var)
    {
        GPBUtil::checkUint64($var);
        $this->clan_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timezone = 3;</code>
     * @return int|string
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * Generated from protobuf field <code>uint64 timezone = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimezone($var)
    {
        GPBUtil::checkUint64($var);
        $this->timezone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 lev = 4;</code>
     * @return int
     */
    public function getLev()
    {
        return $this->lev;
    }

    /**
     * Generated from protobuf field <code>uint32 lev = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLev($var)
    {
        GPBUtil::checkUint32($var);
        $this->lev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 exp = 5;</code>
     * @return int
     */
    public function getExp()
    {
        return $this->exp;
    }

    /**
     * Generated from protobuf field <code>uint32 exp = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkUint32($var);
        $this->exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 emblem_id = 6;</code>
     * @return int
     */
    public function getEmblemId()
    {
        return $this->emblem_id;
    }

    /**
     * Generated from protobuf field <code>uint32 emblem_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setEmblemId($var)
    {
        GPBUtil::checkUint32($var);
        $this->emblem_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 member_count = 7;</code>
     * @return int
     */
    public function getMemberCount()
    {
        return $this->member_count;
    }

    /**
     * Generated from protobuf field <code>uint32 member_count = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->member_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_member_count = 8;</code>
     * @return int
     */
    public function getMaxMemberCount()
    {
        return $this->max_member_count;
    }

    /**
     * Generated from protobuf field <code>uint32 max_member_count = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxMemberCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_member_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 vice_master_count = 9;</code>
     * @return int
     */
    public function getViceMasterCount()
    {
        return $this->vice_master_count;
    }

    /**
     * Generated from protobuf field <code>uint32 vice_master_count = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setViceMasterCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->vice_master_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 join_season_count = 10;</code>
     * @return int
     */
    public function getJoinSeasonCount()
    {
        return $this->join_season_count;
    }

    /**
     * Generated from protobuf field <code>uint32 join_season_count = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setJoinSeasonCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->join_season_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_boss_lev = 11;</code>
     * @return int
     */
    public function getMaxBossLev()
    {
        return $this->max_boss_lev;
    }

    /**
     * Generated from protobuf field <code>uint32 max_boss_lev = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxBossLev($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_boss_lev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 best_cvc_rank = 12;</code>
     * @return int
     */
    public function getBestCvcRank()
    {
        return $this->best_cvc_rank;
    }

    /**
     * Generated from protobuf field <code>uint32 best_cvc_rank = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setBestCvcRank($var)
    {
        GPBUtil::checkUint32($var);
        $this->best_cvc_rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chatting_notice = 13;</code>
     * @return string
     */
    public function getChattingNotice()
    {
        return $this->chatting_notice;
    }

    /**
     * Generated from protobuf field <code>string chatting_notice = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setChattingNotice($var)
    {
        GPBUtil::checkString($var, True);
        $this->chatting_notice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 14;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clan_festival_message = 15;</code>
     * @return string
     */
    public function getClanFestivalMessage()
    {
        return $this->clan_festival_message;
    }

    /**
     * Generated from protobuf field <code>string clan_festival_message = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setClanFestivalMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->clan_festival_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string desc = 16;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Generated from protobuf field <code>string desc = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 17;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 req_date = 18;</code>
     * @return int|string
     */
    public function getReqDate()
    {
        return $this->req_date;
    }

    /**
     * Generated from protobuf field <code>uint64 req_date = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReqDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->req_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string private_key = 19;</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->private_key;
    }

    /**
     * Generated from protobuf field <code>string private_key = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string public_key = 20;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>string public_key = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 apprentice_count = 21;</code>
     * @return int
     */
    public function getApprenticeCount()
    {
        return $this->apprentice_count;
    }

    /**
     * Generated from protobuf field <code>uint32 apprentice_count = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setApprenticeCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->apprentice_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 attendance_count = 22;</code>
     * @return int
     */
    public function getAttendanceCount()
    {
        return $this->attendance_count;
    }

    /**
     * Generated from protobuf field <code>uint32 attendance_count = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setAttendanceCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->attendance_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.CVCSeasonState cvc_season_state = 23;</code>
     * @return int
     */
    public function getCvcSeasonState()
    {
        return $this->cvc_season_state;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.CVCSeasonState cvc_season_state = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setCvcSeasonState($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\CVCSeasonState::class);
        $this->cvc_season_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cvc_battle_phase_count = 24;</code>
     * @return int
     */
    public function getCvcBattlePhaseCount()
    {
        return $this->cvc_battle_phase_count;
    }

    /**
     * Generated from protobuf field <code>uint32 cvc_battle_phase_count = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setCvcBattlePhaseCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->cvc_battle_phase_count = $var;

        return $this;
    }

}

