<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgCheckDailyBonus.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgCheckDailyBonus</code>
 */
class MsgCheckDailyBonus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool daily_bonus_updated = 1;</code>
     */
    private $daily_bonus_updated = false;
    /**
     * Generated from protobuf field <code>fixed32 daily_bonus_running = 2;</code>
     */
    private $daily_bonus_running = 0;
    /**
     * Generated from protobuf field <code>uint32 daily_bonus_recv_cnt = 3;</code>
     */
    private $daily_bonus_recv_cnt = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift daily_bonus_recv_gift = 4;</code>
     */
    private $daily_bonus_recv_gift = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgDailyBonus.MsgDailyBonusType bonus_type = 5;</code>
     */
    private $bonus_type = 0;

    public function __construct() {
        \GPBMetadata\MsgCheckDailyBonus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool daily_bonus_updated = 1;</code>
     * @return bool
     */
    public function getDailyBonusUpdated()
    {
        return $this->daily_bonus_updated;
    }

    /**
     * Generated from protobuf field <code>bool daily_bonus_updated = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setDailyBonusUpdated($var)
    {
        GPBUtil::checkBool($var);
        $this->daily_bonus_updated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 daily_bonus_running = 2;</code>
     * @return int
     */
    public function getDailyBonusRunning()
    {
        return $this->daily_bonus_running;
    }

    /**
     * Generated from protobuf field <code>fixed32 daily_bonus_running = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDailyBonusRunning($var)
    {
        GPBUtil::checkUint32($var);
        $this->daily_bonus_running = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 daily_bonus_recv_cnt = 3;</code>
     * @return int
     */
    public function getDailyBonusRecvCnt()
    {
        return $this->daily_bonus_recv_cnt;
    }

    /**
     * Generated from protobuf field <code>uint32 daily_bonus_recv_cnt = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDailyBonusRecvCnt($var)
    {
        GPBUtil::checkUint32($var);
        $this->daily_bonus_recv_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift daily_bonus_recv_gift = 4;</code>
     * @return \Msggamedata\MsgUserGift
     */
    public function getDailyBonusRecvGift()
    {
        return $this->daily_bonus_recv_gift;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift daily_bonus_recv_gift = 4;</code>
     * @param \Msggamedata\MsgUserGift $var
     * @return $this
     */
    public function setDailyBonusRecvGift($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserGift::class);
        $this->daily_bonus_recv_gift = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgDailyBonus.MsgDailyBonusType bonus_type = 5;</code>
     * @return int
     */
    public function getBonusType()
    {
        return $this->bonus_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgDailyBonus.MsgDailyBonusType bonus_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBonusType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgDailyBonus_MsgDailyBonusType::class);
        $this->bonus_type = $var;

        return $this;
    }

}

