<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgClanSubStage.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgClanSubStage</code>
 */
class MsgClanSubStage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>uint32 stage_uid = 2;</code>
     */
    private $stage_uid = 0;
    /**
     * Generated from protobuf field <code>uint32 boss_lev = 3;</code>
     */
    private $boss_lev = 0;
    /**
     * Generated from protobuf field <code>string boss_start_scene = 4;</code>
     */
    private $boss_start_scene = '';
    /**
     * Generated from protobuf field <code>string img = 5;</code>
     */
    private $img = '';
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgStageBattle battles = 6;</code>
     */
    private $battles;

    public function __construct() {
        \GPBMetadata\MsgClanSubStage::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 stage_uid = 2;</code>
     * @return int
     */
    public function getStageUid()
    {
        return $this->stage_uid;
    }

    /**
     * Generated from protobuf field <code>uint32 stage_uid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStageUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->stage_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 boss_lev = 3;</code>
     * @return int
     */
    public function getBossLev()
    {
        return $this->boss_lev;
    }

    /**
     * Generated from protobuf field <code>uint32 boss_lev = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBossLev($var)
    {
        GPBUtil::checkUint32($var);
        $this->boss_lev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string boss_start_scene = 4;</code>
     * @return string
     */
    public function getBossStartScene()
    {
        return $this->boss_start_scene;
    }

    /**
     * Generated from protobuf field <code>string boss_start_scene = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBossStartScene($var)
    {
        GPBUtil::checkString($var, True);
        $this->boss_start_scene = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string img = 5;</code>
     * @return string
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * Generated from protobuf field <code>string img = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->img = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgStageBattle battles = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBattles()
    {
        return $this->battles;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgStageBattle battles = 6;</code>
     * @param \Msggamedata\MsgStageBattle[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBattles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgStageBattle::class);
        $this->battles = $arr;

        return $this;
    }

}

