<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgChatLikeColor.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MsgChatLikeColor\ChatColorType</code>
 */
class MsgChatLikeColor_ChatColorType
{
    /**
     * Generated from protobuf enum <code>CCT_NONE = 0;</code>
     */
    const CCT_NONE = 0;
    /**
     * Generated from protobuf enum <code>CCT_CLAN_VS = 1;</code>
     */
    const CCT_CLAN_VS = 1;
}

