<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgDailyBonus.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgDailyBonus.MsgDailyBonusItem</code>
 */
class MsgDailyBonus_MsgDailyBonusItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 day = 1;</code>
     */
    private $day = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItem.ItemType item_type = 2;</code>
     */
    private $item_type = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount uid_data = 3;</code>
     */
    private $uid_data = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaInstantMonster instant_monster_meta = 4;</code>
     */
    private $instant_monster_meta = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgDailyBonus.MsgDailyBonusItemShowType show_type = 5;</code>
     */
    private $show_type = 0;
    /**
     * Generated from protobuf field <code>string ext_img = 6;</code>
     */
    private $ext_img = '';
    /**
     * Generated from protobuf field <code>fixed32 talk_seq_uid = 7;</code>
     */
    private $talk_seq_uid = 0;
    /**
     * Generated from protobuf field <code>fixed32 promise_uid = 8;</code>
     */
    private $promise_uid = 0;

    public function __construct() {
        \GPBMetadata\MsgDailyBonus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 day = 1;</code>
     * @return int
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * Generated from protobuf field <code>uint32 day = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkUint32($var);
        $this->day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItem.ItemType item_type = 2;</code>
     * @return int
     */
    public function getItemType()
    {
        return $this->item_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItem.ItemType item_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setItemType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgShopItem_ItemType::class);
        $this->item_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount uid_data = 3;</code>
     * @return \Msggamedata\MsgUidAndAmount
     */
    public function getUidData()
    {
        return $this->uid_data;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount uid_data = 3;</code>
     * @param \Msggamedata\MsgUidAndAmount $var
     * @return $this
     */
    public function setUidData($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUidAndAmount::class);
        $this->uid_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaInstantMonster instant_monster_meta = 4;</code>
     * @return \Msggamedata\MsgShopItemMetaInstantMonster
     */
    public function getInstantMonsterMeta()
    {
        return $this->instant_monster_meta;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaInstantMonster instant_monster_meta = 4;</code>
     * @param \Msggamedata\MsgShopItemMetaInstantMonster $var
     * @return $this
     */
    public function setInstantMonsterMeta($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgShopItemMetaInstantMonster::class);
        $this->instant_monster_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgDailyBonus.MsgDailyBonusItemShowType show_type = 5;</code>
     * @return int
     */
    public function getShowType()
    {
        return $this->show_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgDailyBonus.MsgDailyBonusItemShowType show_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setShowType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgDailyBonus_MsgDailyBonusItemShowType::class);
        $this->show_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ext_img = 6;</code>
     * @return string
     */
    public function getExtImg()
    {
        return $this->ext_img;
    }

    /**
     * Generated from protobuf field <code>string ext_img = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setExtImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->ext_img = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 talk_seq_uid = 7;</code>
     * @return int
     */
    public function getTalkSeqUid()
    {
        return $this->talk_seq_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 talk_seq_uid = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTalkSeqUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->talk_seq_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 promise_uid = 8;</code>
     * @return int
     */
    public function getPromiseUid()
    {
        return $this->promise_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 promise_uid = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPromiseUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->promise_uid = $var;

        return $this;
    }

}

