<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgDailyBonusSeason.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgDailyBonusSeason</code>
 */
class MsgDailyBonusSeason extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>string season = 2;</code>
     */
    private $season = '';
    /**
     * Generated from protobuf field <code>fixed32 normal_table = 3;</code>
     */
    private $normal_table = 0;
    /**
     * Generated from protobuf field <code>fixed32 return_table = 4;</code>
     */
    private $return_table = 0;
    /**
     * Generated from protobuf field <code>fixed32 newuser_table = 5;</code>
     */
    private $newuser_table = 0;
    /**
     * Generated from protobuf field <code>fixed32 contractor = 6;</code>
     */
    private $contractor = 0;
    /**
     * Generated from protobuf field <code>fixed32 contract_daily_bonus = 7;</code>
     */
    private $contract_daily_bonus = 0;
    /**
     * Generated from protobuf field <code>fixed32 light_contractor = 8;</code>
     */
    private $light_contractor = 0;
    /**
     * Generated from protobuf field <code>fixed32 light_contract_bonus = 9;</code>
     */
    private $light_contract_bonus = 0;

    public function __construct() {
        \GPBMetadata\MsgDailyBonusSeason::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string season = 2;</code>
     * @return string
     */
    public function getSeason()
    {
        return $this->season;
    }

    /**
     * Generated from protobuf field <code>string season = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSeason($var)
    {
        GPBUtil::checkString($var, True);
        $this->season = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 normal_table = 3;</code>
     * @return int
     */
    public function getNormalTable()
    {
        return $this->normal_table;
    }

    /**
     * Generated from protobuf field <code>fixed32 normal_table = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNormalTable($var)
    {
        GPBUtil::checkUint32($var);
        $this->normal_table = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 return_table = 4;</code>
     * @return int
     */
    public function getReturnTable()
    {
        return $this->return_table;
    }

    /**
     * Generated from protobuf field <code>fixed32 return_table = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setReturnTable($var)
    {
        GPBUtil::checkUint32($var);
        $this->return_table = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 newuser_table = 5;</code>
     * @return int
     */
    public function getNewuserTable()
    {
        return $this->newuser_table;
    }

    /**
     * Generated from protobuf field <code>fixed32 newuser_table = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNewuserTable($var)
    {
        GPBUtil::checkUint32($var);
        $this->newuser_table = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 contractor = 6;</code>
     * @return int
     */
    public function getContractor()
    {
        return $this->contractor;
    }

    /**
     * Generated from protobuf field <code>fixed32 contractor = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setContractor($var)
    {
        GPBUtil::checkUint32($var);
        $this->contractor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 contract_daily_bonus = 7;</code>
     * @return int
     */
    public function getContractDailyBonus()
    {
        return $this->contract_daily_bonus;
    }

    /**
     * Generated from protobuf field <code>fixed32 contract_daily_bonus = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setContractDailyBonus($var)
    {
        GPBUtil::checkUint32($var);
        $this->contract_daily_bonus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 light_contractor = 8;</code>
     * @return int
     */
    public function getLightContractor()
    {
        return $this->light_contractor;
    }

    /**
     * Generated from protobuf field <code>fixed32 light_contractor = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLightContractor($var)
    {
        GPBUtil::checkUint32($var);
        $this->light_contractor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 light_contract_bonus = 9;</code>
     * @return int
     */
    public function getLightContractBonus()
    {
        return $this->light_contract_bonus;
    }

    /**
     * Generated from protobuf field <code>fixed32 light_contract_bonus = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setLightContractBonus($var)
    {
        GPBUtil::checkUint32($var);
        $this->light_contract_bonus = $var;

        return $this;
    }

}

