<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgGameString.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgGameString</code>
 */
class MsgGameString extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgLocalizedString strings = 1;</code>
     */
    private $strings;

    public function __construct() {
        \GPBMetadata\MsgGameString::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgLocalizedString strings = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStrings()
    {
        return $this->strings;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgLocalizedString strings = 1;</code>
     * @param \Msggamedata\MsgLocalizedString[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStrings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgLocalizedString::class);
        $this->strings = $arr;

        return $this;
    }

}

