<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgGiftItem.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgGiftItem</code>
 */
class MsgGiftItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem v_user_item = 1;</code>
     */
    private $v_user_item = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserRune v_user_rune = 2;</code>
     */
    private $v_user_rune = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster v_user_monster = 3;</code>
     */
    private $v_user_monster = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterDictData v_user_monster_dict = 4;</code>
     */
    private $v_user_monster_dict = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterSkillBook v_skill_book = 5;</code>
     */
    private $v_skill_book = null;

    public function __construct() {
        \GPBMetadata\MsgGiftItem::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem v_user_item = 1;</code>
     * @return \Msggamedata\MsgUserItem
     */
    public function getVUserItem()
    {
        return $this->v_user_item;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem v_user_item = 1;</code>
     * @param \Msggamedata\MsgUserItem $var
     * @return $this
     */
    public function setVUserItem($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserItem::class);
        $this->v_user_item = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserRune v_user_rune = 2;</code>
     * @return \Msggamedata\MsgUserRune
     */
    public function getVUserRune()
    {
        return $this->v_user_rune;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserRune v_user_rune = 2;</code>
     * @param \Msggamedata\MsgUserRune $var
     * @return $this
     */
    public function setVUserRune($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserRune::class);
        $this->v_user_rune = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster v_user_monster = 3;</code>
     * @return \Msggamedata\MsgUserMonster
     */
    public function getVUserMonster()
    {
        return $this->v_user_monster;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster v_user_monster = 3;</code>
     * @param \Msggamedata\MsgUserMonster $var
     * @return $this
     */
    public function setVUserMonster($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonster::class);
        $this->v_user_monster = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterDictData v_user_monster_dict = 4;</code>
     * @return \Msggamedata\MsgUserMonsterDictData
     */
    public function getVUserMonsterDict()
    {
        return $this->v_user_monster_dict;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterDictData v_user_monster_dict = 4;</code>
     * @param \Msggamedata\MsgUserMonsterDictData $var
     * @return $this
     */
    public function setVUserMonsterDict($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonsterDictData::class);
        $this->v_user_monster_dict = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterSkillBook v_skill_book = 5;</code>
     * @return \Msggamedata\MsgUserMonsterSkillBook
     */
    public function getVSkillBook()
    {
        return $this->v_skill_book;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterSkillBook v_skill_book = 5;</code>
     * @param \Msggamedata\MsgUserMonsterSkillBook $var
     * @return $this
     */
    public function setVSkillBook($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonsterSkillBook::class);
        $this->v_skill_book = $var;

        return $this;
    }

}

