<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgLobbyReward.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgLobbyReward</code>
 */
class MsgLobbyReward extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgLobbyReward.LobbyRewardType reward_type = 2;</code>
     */
    private $reward_type = 0;
    /**
     * Generated from protobuf field <code>uint32 max_cnt = 3;</code>
     */
    private $max_cnt = 0;
    /**
     * Generated from protobuf field <code>uint32 cool_time = 4;</code>
     */
    private $cool_time = 0;
    /**
     * Generated from protobuf field <code>string open_time = 5;</code>
     */
    private $open_time = '';
    /**
     * Generated from protobuf field <code>string close_time = 6;</code>
     */
    private $close_time = '';
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount reward = 7;</code>
     */
    private $reward = null;
    /**
     * Generated from protobuf field <code>uint32 last_reward = 8;</code>
     */
    private $last_reward = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.ShipLobbyType ship_types = 9;</code>
     */
    private $ship_types;

    public function __construct() {
        \GPBMetadata\MsgLobbyReward::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>uint32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgLobbyReward.LobbyRewardType reward_type = 2;</code>
     * @return int
     */
    public function getRewardType()
    {
        return $this->reward_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgLobbyReward.LobbyRewardType reward_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRewardType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgLobbyReward_LobbyRewardType::class);
        $this->reward_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_cnt = 3;</code>
     * @return int
     */
    public function getMaxCnt()
    {
        return $this->max_cnt;
    }

    /**
     * Generated from protobuf field <code>uint32 max_cnt = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxCnt($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cool_time = 4;</code>
     * @return int
     */
    public function getCoolTime()
    {
        return $this->cool_time;
    }

    /**
     * Generated from protobuf field <code>uint32 cool_time = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCoolTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->cool_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string open_time = 5;</code>
     * @return string
     */
    public function getOpenTime()
    {
        return $this->open_time;
    }

    /**
     * Generated from protobuf field <code>string open_time = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string close_time = 6;</code>
     * @return string
     */
    public function getCloseTime()
    {
        return $this->close_time;
    }

    /**
     * Generated from protobuf field <code>string close_time = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCloseTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->close_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount reward = 7;</code>
     * @return \Msggamedata\MsgUidAndAmount
     */
    public function getReward()
    {
        return $this->reward;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount reward = 7;</code>
     * @param \Msggamedata\MsgUidAndAmount $var
     * @return $this
     */
    public function setReward($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUidAndAmount::class);
        $this->reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 last_reward = 8;</code>
     * @return int
     */
    public function getLastReward()
    {
        return $this->last_reward;
    }

    /**
     * Generated from protobuf field <code>uint32 last_reward = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLastReward($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.ShipLobbyType ship_types = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShipTypes()
    {
        return $this->ship_types;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.ShipLobbyType ship_types = 9;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShipTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Msggamedata\ShipLobbyType::class);
        $this->ship_types = $arr;

        return $this;
    }

}

