<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgMonthlyMonsterData.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgMonthlyMonsterData</code>
 */
class MsgMonthlyMonsterData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>fixed32 monster_uid = 2;</code>
     */
    private $monster_uid = 0;
    /**
     * Generated from protobuf field <code>uint64 release_date = 3;</code>
     */
    private $release_date = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut ui_shortcut = 4;</code>
     */
    private $ui_shortcut = null;
    /**
     * Generated from protobuf field <code>fixed32 ui_shortcut_str = 5;</code>
     */
    private $ui_shortcut_str = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgQuest.MainCondi main_condi = 6;</code>
     */
    private $main_condi = 0;
    /**
     * Generated from protobuf field <code>uint32 goal_count = 7;</code>
     */
    private $goal_count = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgQuestSubCondi sub_condis = 8;</code>
     */
    private $sub_condis;
    /**
     * Generated from protobuf field <code>fixed32 quest_str = 9;</code>
     */
    private $quest_str = 0;
    /**
     * Generated from protobuf field <code>float league_buff_multiply = 10;</code>
     */
    private $league_buff_multiply = 0.0;
    /**
     * Generated from protobuf field <code>string bg_prefab = 11;</code>
     */
    private $bg_prefab = '';
    /**
     * Generated from protobuf field <code>fixed32 costume_bundle_uid = 12;</code>
     */
    private $costume_bundle_uid = 0;
    /**
     * Generated from protobuf field <code>float size_factor = 13;</code>
     */
    private $size_factor = 0.0;

    public function __construct() {
        \GPBMetadata\MsgMonthlyMonsterData::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 monster_uid = 2;</code>
     * @return int
     */
    public function getMonsterUid()
    {
        return $this->monster_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 monster_uid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMonsterUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->monster_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 release_date = 3;</code>
     * @return int|string
     */
    public function getReleaseDate()
    {
        return $this->release_date;
    }

    /**
     * Generated from protobuf field <code>uint64 release_date = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReleaseDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->release_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut ui_shortcut = 4;</code>
     * @return \Msggamedata\MsgUIShortcut
     */
    public function getUiShortcut()
    {
        return $this->ui_shortcut;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut ui_shortcut = 4;</code>
     * @param \Msggamedata\MsgUIShortcut $var
     * @return $this
     */
    public function setUiShortcut($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUIShortcut::class);
        $this->ui_shortcut = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 ui_shortcut_str = 5;</code>
     * @return int
     */
    public function getUiShortcutStr()
    {
        return $this->ui_shortcut_str;
    }

    /**
     * Generated from protobuf field <code>fixed32 ui_shortcut_str = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setUiShortcutStr($var)
    {
        GPBUtil::checkUint32($var);
        $this->ui_shortcut_str = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgQuest.MainCondi main_condi = 6;</code>
     * @return int
     */
    public function getMainCondi()
    {
        return $this->main_condi;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgQuest.MainCondi main_condi = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMainCondi($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgQuest_MainCondi::class);
        $this->main_condi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 goal_count = 7;</code>
     * @return int
     */
    public function getGoalCount()
    {
        return $this->goal_count;
    }

    /**
     * Generated from protobuf field <code>uint32 goal_count = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setGoalCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->goal_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgQuestSubCondi sub_condis = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubCondis()
    {
        return $this->sub_condis;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgQuestSubCondi sub_condis = 8;</code>
     * @param \Msggamedata\MsgQuestSubCondi[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubCondis($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgQuestSubCondi::class);
        $this->sub_condis = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 quest_str = 9;</code>
     * @return int
     */
    public function getQuestStr()
    {
        return $this->quest_str;
    }

    /**
     * Generated from protobuf field <code>fixed32 quest_str = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setQuestStr($var)
    {
        GPBUtil::checkUint32($var);
        $this->quest_str = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float league_buff_multiply = 10;</code>
     * @return float
     */
    public function getLeagueBuffMultiply()
    {
        return $this->league_buff_multiply;
    }

    /**
     * Generated from protobuf field <code>float league_buff_multiply = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setLeagueBuffMultiply($var)
    {
        GPBUtil::checkFloat($var);
        $this->league_buff_multiply = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bg_prefab = 11;</code>
     * @return string
     */
    public function getBgPrefab()
    {
        return $this->bg_prefab;
    }

    /**
     * Generated from protobuf field <code>string bg_prefab = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setBgPrefab($var)
    {
        GPBUtil::checkString($var, True);
        $this->bg_prefab = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 costume_bundle_uid = 12;</code>
     * @return int
     */
    public function getCostumeBundleUid()
    {
        return $this->costume_bundle_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 costume_bundle_uid = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setCostumeBundleUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->costume_bundle_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float size_factor = 13;</code>
     * @return float
     */
    public function getSizeFactor()
    {
        return $this->size_factor;
    }

    /**
     * Generated from protobuf field <code>float size_factor = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setSizeFactor($var)
    {
        GPBUtil::checkFloat($var);
        $this->size_factor = $var;

        return $this;
    }

}

