<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgMonsterAi.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgMonsterAi</code>
 */
class MsgMonsterAi extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>fixed32 fail_over = 2;</code>
     */
    private $fail_over = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond1 = 3;</code>
     */
    private $cond1;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond2 = 4;</code>
     */
    private $cond2;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond3 = 5;</code>
     */
    private $cond3;

    public function __construct() {
        \GPBMetadata\MsgMonsterAi::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 fail_over = 2;</code>
     * @return int
     */
    public function getFailOver()
    {
        return $this->fail_over;
    }

    /**
     * Generated from protobuf field <code>fixed32 fail_over = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFailOver($var)
    {
        GPBUtil::checkUint32($var);
        $this->fail_over = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond1 = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCond1()
    {
        return $this->cond1;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond1 = 3;</code>
     * @param \Msggamedata\MsgMonsterAiItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCond1($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgMonsterAiItem::class);
        $this->cond1 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond2 = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCond2()
    {
        return $this->cond2;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond2 = 4;</code>
     * @param \Msggamedata\MsgMonsterAiItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCond2($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgMonsterAiItem::class);
        $this->cond2 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond3 = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCond3()
    {
        return $this->cond3;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgMonsterAiItem cond3 = 5;</code>
     * @param \Msggamedata\MsgMonsterAiItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCond3($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgMonsterAiItem::class);
        $this->cond3 = $arr;

        return $this;
    }

}

