<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgNPCTalkSequence.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgNPCTalkSequence</code>
 */
class MsgNPCTalkSequence extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgNPCTalk talks = 2;</code>
     */
    private $talks;

    public function __construct() {
        \GPBMetadata\MsgNPCTalkSequence::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgNPCTalk talks = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTalks()
    {
        return $this->talks;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgNPCTalk talks = 2;</code>
     * @param \Msggamedata\MsgNPCTalk[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTalks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgNPCTalk::class);
        $this->talks = $arr;

        return $this;
    }

}

