<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgPackagePurchaseBonus.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgPackagePurchaseBonus</code>
 */
class MsgPackagePurchaseBonus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     */
    private $count = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.RewardDataType data_type = 2;</code>
     */
    private $data_type = 0;
    /**
     * Generated from protobuf field <code>uint32 value_data = 3;</code>
     */
    private $value_data = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount uid_data = 4;</code>
     */
    private $uid_data = null;
    /**
     * Generated from protobuf field <code>fixed32 gift_temp = 5;</code>
     */
    private $gift_temp = 0;

    public function __construct() {
        \GPBMetadata\MsgPackagePurchaseBonus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.RewardDataType data_type = 2;</code>
     * @return int
     */
    public function getDataType()
    {
        return $this->data_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.RewardDataType data_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDataType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\RewardDataType::class);
        $this->data_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 value_data = 3;</code>
     * @return int
     */
    public function getValueData()
    {
        return $this->value_data;
    }

    /**
     * Generated from protobuf field <code>uint32 value_data = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setValueData($var)
    {
        GPBUtil::checkUint32($var);
        $this->value_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount uid_data = 4;</code>
     * @return \Msggamedata\MsgUidAndAmount
     */
    public function getUidData()
    {
        return $this->uid_data;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUidAndAmount uid_data = 4;</code>
     * @param \Msggamedata\MsgUidAndAmount $var
     * @return $this
     */
    public function setUidData($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUidAndAmount::class);
        $this->uid_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 gift_temp = 5;</code>
     * @return int
     */
    public function getGiftTemp()
    {
        return $this->gift_temp;
    }

    /**
     * Generated from protobuf field <code>fixed32 gift_temp = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setGiftTemp($var)
    {
        GPBUtil::checkUint32($var);
        $this->gift_temp = $var;

        return $this;
    }

}

