<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgPackageUidAndType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MsgPackageUidAndType\PackageRewardType</code>
 */
class MsgPackageUidAndType_PackageRewardType
{
    /**
     * Generated from protobuf enum <code>RewardTypeNone = 0;</code>
     */
    const RewardTypeNone = 0;
    /**
     * Generated from protobuf enum <code>RewardTypeFree = 1;</code>
     */
    const RewardTypeFree = 1;
    /**
     * Generated from protobuf enum <code>RewardTypePurchase = 2;</code>
     */
    const RewardTypePurchase = 2;
}

