<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgPlatformAchievement.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgPlatformAchievement</code>
 */
class MsgPlatformAchievement extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>fixed32 data = 2;</code>
     */
    private $data = 0;
    /**
     * Generated from protobuf field <code>string ios_code = 3;</code>
     */
    private $ios_code = '';
    /**
     * Generated from protobuf field <code>string android_code = 4;</code>
     */
    private $android_code = '';

    public function __construct() {
        \GPBMetadata\MsgPlatformAchievement::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 data = 2;</code>
     * @return int
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>fixed32 data = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkUint32($var);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ios_code = 3;</code>
     * @return string
     */
    public function getIosCode()
    {
        return $this->ios_code;
    }

    /**
     * Generated from protobuf field <code>string ios_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIosCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ios_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string android_code = 4;</code>
     * @return string
     */
    public function getAndroidCode()
    {
        return $this->android_code;
    }

    /**
     * Generated from protobuf field <code>string android_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAndroidCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->android_code = $var;

        return $this;
    }

}

