<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgQuestSubCondi.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MsgQuestSubCondi\CategoryTypeL</code>
 */
class MsgQuestSubCondi_CategoryTypeL
{
    /**
     * Generated from protobuf enum <code>CategoryTypeNULL = 0;</code>
     */
    const CategoryTypeNULL = 0;
    /**
     * Generated from protobuf enum <code>CT_Cash = 1;</code>
     */
    const CT_Cash = 1;
    /**
     * Generated from protobuf enum <code>CT_Rune = 2;</code>
     */
    const CT_Rune = 2;
    /**
     * Generated from protobuf enum <code>CT_BeyondStone = 3;</code>
     */
    const CT_BeyondStone = 3;
    /**
     * Generated from protobuf enum <code>CT_Monster = 4;</code>
     */
    const CT_Monster = 4;
    /**
     * Generated from protobuf enum <code>CT_Capture = 5;</code>
     */
    const CT_Capture = 5;
    /**
     * Generated from protobuf enum <code>CT_InstantGold = 6;</code>
     */
    const CT_InstantGold = 6;
    /**
     * Generated from protobuf enum <code>CT_Joje = 7;</code>
     */
    const CT_Joje = 7;
    /**
     * Generated from protobuf enum <code>CT_ProfileIcon = 8;</code>
     */
    const CT_ProfileIcon = 8;
    /**
     * Generated from protobuf enum <code>CT_Package = 9;</code>
     */
    const CT_Package = 9;
    /**
     * Generated from protobuf enum <code>CT_ItemBundle = 10;</code>
     */
    const CT_ItemBundle = 10;
    /**
     * Generated from protobuf enum <code>CT_Crystal = 11;</code>
     */
    const CT_Crystal = 11;
    /**
     * Generated from protobuf enum <code>CT_Clan = 12;</code>
     */
    const CT_Clan = 12;
    /**
     * Generated from protobuf enum <code>CT_Etc = 50;</code>
     */
    const CT_Etc = 50;
}

