<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgReviveMonster.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgReviveMonster</code>
 */
class MsgReviveMonster extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>fixed32 name = 2;</code>
     */
    private $name = 0;
    /**
     * Generated from protobuf field <code>fixed32 desc = 3;</code>
     */
    private $desc = 0;
    /**
     * Generated from protobuf field <code>uint64 open_date = 4;</code>
     */
    private $open_date = 0;
    /**
     * Generated from protobuf field <code>uint64 close_date = 5;</code>
     */
    private $close_date = 0;
    /**
     * Generated from protobuf field <code>fixed32 revive_monsters_uid = 6;</code>
     */
    private $revive_monsters_uid = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice price = 7;</code>
     */
    private $price = null;
    /**
     * Generated from protobuf field <code>fixed32 cutscene_uid = 8;</code>
     */
    private $cutscene_uid = 0;
    /**
     * Generated from protobuf field <code>string egg = 9;</code>
     */
    private $egg = '';
    /**
     * Generated from protobuf field <code>uint32 min_grade = 10;</code>
     */
    private $min_grade = 0;
    /**
     * Generated from protobuf field <code>uint32 max_grade = 11;</code>
     */
    private $max_grade = 0;
    /**
     * Generated from protobuf field <code>uint32 special_count = 12;</code>
     */
    private $special_count = 0;
    /**
     * Generated from protobuf field <code>fixed32 special_reward = 13;</code>
     */
    private $special_reward = 0;
    /**
     * Generated from protobuf field <code>repeated fixed32 ban_monster_uids = 14;</code>
     */
    private $ban_monster_uids;

    public function __construct() {
        \GPBMetadata\MsgReviveMonster::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 name = 2;</code>
     * @return int
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>fixed32 name = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkUint32($var);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 desc = 3;</code>
     * @return int
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Generated from protobuf field <code>fixed32 desc = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkUint32($var);
        $this->desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 open_date = 4;</code>
     * @return int|string
     */
    public function getOpenDate()
    {
        return $this->open_date;
    }

    /**
     * Generated from protobuf field <code>uint64 open_date = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpenDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->open_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 close_date = 5;</code>
     * @return int|string
     */
    public function getCloseDate()
    {
        return $this->close_date;
    }

    /**
     * Generated from protobuf field <code>uint64 close_date = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCloseDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->close_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 revive_monsters_uid = 6;</code>
     * @return int
     */
    public function getReviveMonstersUid()
    {
        return $this->revive_monsters_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 revive_monsters_uid = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setReviveMonstersUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->revive_monsters_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice price = 7;</code>
     * @return \Msggamedata\MsgPrice
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice price = 7;</code>
     * @param \Msggamedata\MsgPrice $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgPrice::class);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 cutscene_uid = 8;</code>
     * @return int
     */
    public function getCutsceneUid()
    {
        return $this->cutscene_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 cutscene_uid = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setCutsceneUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->cutscene_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string egg = 9;</code>
     * @return string
     */
    public function getEgg()
    {
        return $this->egg;
    }

    /**
     * Generated from protobuf field <code>string egg = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setEgg($var)
    {
        GPBUtil::checkString($var, True);
        $this->egg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 min_grade = 10;</code>
     * @return int
     */
    public function getMinGrade()
    {
        return $this->min_grade;
    }

    /**
     * Generated from protobuf field <code>uint32 min_grade = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setMinGrade($var)
    {
        GPBUtil::checkUint32($var);
        $this->min_grade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_grade = 11;</code>
     * @return int
     */
    public function getMaxGrade()
    {
        return $this->max_grade;
    }

    /**
     * Generated from protobuf field <code>uint32 max_grade = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxGrade($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_grade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 special_count = 12;</code>
     * @return int
     */
    public function getSpecialCount()
    {
        return $this->special_count;
    }

    /**
     * Generated from protobuf field <code>uint32 special_count = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setSpecialCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->special_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 special_reward = 13;</code>
     * @return int
     */
    public function getSpecialReward()
    {
        return $this->special_reward;
    }

    /**
     * Generated from protobuf field <code>fixed32 special_reward = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setSpecialReward($var)
    {
        GPBUtil::checkUint32($var);
        $this->special_reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated fixed32 ban_monster_uids = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBanMonsterUids()
    {
        return $this->ban_monster_uids;
    }

    /**
     * Generated from protobuf field <code>repeated fixed32 ban_monster_uids = 14;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBanMonsterUids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED32);
        $this->ban_monster_uids = $arr;

        return $this;
    }

}

