<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgRspBattleStartScenario.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgRspBattleStartScenario</code>
 */
class MsgRspBattleStartScenario extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleStartBasicInfo basic_info = 1;</code>
     */
    private $basic_info = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleFriend battle_friend = 2;</code>
     */
    private $battle_friend = null;
    /**
     * Generated from protobuf field <code>.msggamedata.StageDifficultyType difficulty = 3;</code>
     */
    private $difficulty = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgSupportMonsterHistory support_monster_history = 4;</code>
     */
    private $support_monster_history = null;
    /**
     * Generated from protobuf field <code>bool enforcement_value_enabled = 5;</code>
     */
    private $enforcement_value_enabled = false;

    public function __construct() {
        \GPBMetadata\MsgRspBattleStartScenario::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleStartBasicInfo basic_info = 1;</code>
     * @return \Msggamedata\MsgBattleStartBasicInfo
     */
    public function getBasicInfo()
    {
        return $this->basic_info;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleStartBasicInfo basic_info = 1;</code>
     * @param \Msggamedata\MsgBattleStartBasicInfo $var
     * @return $this
     */
    public function setBasicInfo($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgBattleStartBasicInfo::class);
        $this->basic_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleFriend battle_friend = 2;</code>
     * @return \Msggamedata\MsgBattleFriend
     */
    public function getBattleFriend()
    {
        return $this->battle_friend;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleFriend battle_friend = 2;</code>
     * @param \Msggamedata\MsgBattleFriend $var
     * @return $this
     */
    public function setBattleFriend($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgBattleFriend::class);
        $this->battle_friend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.StageDifficultyType difficulty = 3;</code>
     * @return int
     */
    public function getDifficulty()
    {
        return $this->difficulty;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.StageDifficultyType difficulty = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDifficulty($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\StageDifficultyType::class);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgSupportMonsterHistory support_monster_history = 4;</code>
     * @return \Msggamedata\MsgSupportMonsterHistory
     */
    public function getSupportMonsterHistory()
    {
        return $this->support_monster_history;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgSupportMonsterHistory support_monster_history = 4;</code>
     * @param \Msggamedata\MsgSupportMonsterHistory $var
     * @return $this
     */
    public function setSupportMonsterHistory($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgSupportMonsterHistory::class);
        $this->support_monster_history = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enforcement_value_enabled = 5;</code>
     * @return bool
     */
    public function getEnforcementValueEnabled()
    {
        return $this->enforcement_value_enabled;
    }

    /**
     * Generated from protobuf field <code>bool enforcement_value_enabled = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnforcementValueEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enforcement_value_enabled = $var;

        return $this;
    }

}

