<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgRspBattleStartCVC.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgRspBattleStartCVC</code>
 */
class MsgRspBattleStartCVC extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 battle_id = 1;</code>
     */
    private $battle_id = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 2;</code>
     */
    private $user = null;
    /**
     * Generated from protobuf field <code>uint32 user_ship_uid = 3;</code>
     */
    private $user_ship_uid = 0;
    /**
     * Generated from protobuf field <code>uint32 user_clan_ship_score = 4;</code>
     */
    private $user_clan_ship_score = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser enemy_user = 5;</code>
     */
    private $enemy_user = null;
    /**
     * Generated from protobuf field <code>uint32 enemy_ship_uid = 6;</code>
     */
    private $enemy_ship_uid = 0;
    /**
     * Generated from protobuf field <code>uint32 enemy_clan_ship_score = 7;</code>
     */
    private $enemy_clan_ship_score = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgCVCMemberSlotInfo enemy_member_slot_info = 8;</code>
     */
    private $enemy_member_slot_info = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserCVCMonsterSlot monster_slot = 9;</code>
     */
    private $monster_slot = null;
    /**
     * Generated from protobuf field <code>repeated uint64 used_monsters = 10;</code>
     */
    private $used_monsters;

    public function __construct() {
        \GPBMetadata\MsgRspBattleStartCVC::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 battle_id = 1;</code>
     * @return int|string
     */
    public function getBattleId()
    {
        return $this->battle_id;
    }

    /**
     * Generated from protobuf field <code>uint64 battle_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBattleId($var)
    {
        GPBUtil::checkUint64($var);
        $this->battle_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 2;</code>
     * @return \Msggamedata\MsgUser
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 2;</code>
     * @param \Msggamedata\MsgUser $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUser::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_ship_uid = 3;</code>
     * @return int
     */
    public function getUserShipUid()
    {
        return $this->user_ship_uid;
    }

    /**
     * Generated from protobuf field <code>uint32 user_ship_uid = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUserShipUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_ship_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_clan_ship_score = 4;</code>
     * @return int
     */
    public function getUserClanShipScore()
    {
        return $this->user_clan_ship_score;
    }

    /**
     * Generated from protobuf field <code>uint32 user_clan_ship_score = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUserClanShipScore($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_clan_ship_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser enemy_user = 5;</code>
     * @return \Msggamedata\MsgUser
     */
    public function getEnemyUser()
    {
        return $this->enemy_user;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser enemy_user = 5;</code>
     * @param \Msggamedata\MsgUser $var
     * @return $this
     */
    public function setEnemyUser($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUser::class);
        $this->enemy_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 enemy_ship_uid = 6;</code>
     * @return int
     */
    public function getEnemyShipUid()
    {
        return $this->enemy_ship_uid;
    }

    /**
     * Generated from protobuf field <code>uint32 enemy_ship_uid = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setEnemyShipUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->enemy_ship_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 enemy_clan_ship_score = 7;</code>
     * @return int
     */
    public function getEnemyClanShipScore()
    {
        return $this->enemy_clan_ship_score;
    }

    /**
     * Generated from protobuf field <code>uint32 enemy_clan_ship_score = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setEnemyClanShipScore($var)
    {
        GPBUtil::checkUint32($var);
        $this->enemy_clan_ship_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgCVCMemberSlotInfo enemy_member_slot_info = 8;</code>
     * @return \Msggamedata\MsgCVCMemberSlotInfo
     */
    public function getEnemyMemberSlotInfo()
    {
        return $this->enemy_member_slot_info;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgCVCMemberSlotInfo enemy_member_slot_info = 8;</code>
     * @param \Msggamedata\MsgCVCMemberSlotInfo $var
     * @return $this
     */
    public function setEnemyMemberSlotInfo($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgCVCMemberSlotInfo::class);
        $this->enemy_member_slot_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserCVCMonsterSlot monster_slot = 9;</code>
     * @return \Msggamedata\MsgUserCVCMonsterSlot
     */
    public function getMonsterSlot()
    {
        return $this->monster_slot;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserCVCMonsterSlot monster_slot = 9;</code>
     * @param \Msggamedata\MsgUserCVCMonsterSlot $var
     * @return $this
     */
    public function setMonsterSlot($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserCVCMonsterSlot::class);
        $this->monster_slot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 used_monsters = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsedMonsters()
    {
        return $this->used_monsters;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 used_monsters = 10;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsedMonsters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->used_monsters = $arr;

        return $this;
    }

}

