<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgRspBattleEndDungeon.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgRspBattleEndDungeon</code>
 */
class MsgRspBattleEndDungeon extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     */
    private $info = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     */
    private $stage_history = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     */
    private $colossus_stage_history = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     */
    private $clear_history = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     */
    private $colossus_clear_reward = null;

    public function __construct() {
        \GPBMetadata\MsgRspBattleEndDungeon::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     * @return \Msggamedata\MsgBattleEndBasicInfo
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     * @param \Msggamedata\MsgBattleEndBasicInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgBattleEndBasicInfo::class);
        $this->info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     * @return \Msggamedata\MsgUserDungeonStageHistory
     */
    public function getStageHistory()
    {
        return $this->stage_history;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     * @param \Msggamedata\MsgUserDungeonStageHistory $var
     * @return $this
     */
    public function setStageHistory($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserDungeonStageHistory::class);
        $this->stage_history = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     * @return \Msggamedata\MsgUserColossusDungeonStageHistory
     */
    public function getColossusStageHistory()
    {
        return $this->colossus_stage_history;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     * @param \Msggamedata\MsgUserColossusDungeonStageHistory $var
     * @return $this
     */
    public function setColossusStageHistory($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserColossusDungeonStageHistory::class);
        $this->colossus_stage_history = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     * @return \Msggamedata\MsgDungeonBattleClearHistory
     */
    public function getClearHistory()
    {
        return $this->clear_history;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     * @param \Msggamedata\MsgDungeonBattleClearHistory $var
     * @return $this
     */
    public function setClearHistory($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgDungeonBattleClearHistory::class);
        $this->clear_history = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     * @return \Msggamedata\MsgUserMonsterSkillBook
     */
    public function getColossusClearReward()
    {
        return $this->colossus_clear_reward;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     * @param \Msggamedata\MsgUserMonsterSkillBook $var
     * @return $this
     */
    public function setColossusClearReward($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonsterSkillBook::class);
        $this->colossus_clear_reward = $var;

        return $this;
    }

}

