<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgRspBattleEndScenario.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgRspBattleEndScenario</code>
 */
class MsgRspBattleEndScenario extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     */
    private $info = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgScenarioBattleClearHistory clear_history = 2;</code>
     */
    private $clear_history = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgFriendDungeonFindHistory find_friend_dungeon = 3;</code>
     */
    private $find_friend_dungeon = null;

    public function __construct() {
        \GPBMetadata\MsgRspBattleEndScenario::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     * @return \Msggamedata\MsgBattleEndBasicInfo
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     * @param \Msggamedata\MsgBattleEndBasicInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgBattleEndBasicInfo::class);
        $this->info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgScenarioBattleClearHistory clear_history = 2;</code>
     * @return \Msggamedata\MsgScenarioBattleClearHistory
     */
    public function getClearHistory()
    {
        return $this->clear_history;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgScenarioBattleClearHistory clear_history = 2;</code>
     * @param \Msggamedata\MsgScenarioBattleClearHistory $var
     * @return $this
     */
    public function setClearHistory($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgScenarioBattleClearHistory::class);
        $this->clear_history = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgFriendDungeonFindHistory find_friend_dungeon = 3;</code>
     * @return \Msggamedata\MsgFriendDungeonFindHistory
     */
    public function getFindFriendDungeon()
    {
        return $this->find_friend_dungeon;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgFriendDungeonFindHistory find_friend_dungeon = 3;</code>
     * @param \Msggamedata\MsgFriendDungeonFindHistory $var
     * @return $this
     */
    public function setFindFriendDungeon($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgFriendDungeonFindHistory::class);
        $this->find_friend_dungeon = $var;

        return $this;
    }

}

