<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgStageMonster.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MsgStageMonster\MonsterCustomScaleMode</code>
 */
class MsgStageMonster_MonsterCustomScaleMode
{
    /**
     * Generated from protobuf enum <code>ScaleMode_None = 0;</code>
     */
    const ScaleMode_None = 0;
    /**
     * Generated from protobuf enum <code>ScaleMode_Add = 1;</code>
     */
    const ScaleMode_Add = 1;
    /**
     * Generated from protobuf enum <code>ScaleMode_Mul = 2;</code>
     */
    const ScaleMode_Mul = 2;
    /**
     * Generated from protobuf enum <code>ScaleMode_Abs = 3;</code>
     */
    const ScaleMode_Abs = 3;
}

