<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgSummonMaxCountMeta.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgSummonMaxCountMeta</code>
 */
class MsgSummonMaxCountMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 max = 1;</code>
     */
    private $max = 0;

    public function __construct() {
        \GPBMetadata\MsgSummonMaxCountMeta::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 max = 1;</code>
     * @return int
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * Generated from protobuf field <code>uint32 max = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkUint32($var);
        $this->max = $var;

        return $this;
    }

}

