<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgStatusEffect.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MsgStatusEffect\StatusEffectWhere</code>
 */
class MsgStatusEffect_StatusEffectWhere
{
    /**
     * Generated from protobuf enum <code>StatusEffectWhereNULL = 0;</code>
     */
    const StatusEffectWhereNULL = 0;
    /**
     * Generated from protobuf enum <code>SEW_All = 1;</code>
     */
    const SEW_All = 1;
    /**
     * Generated from protobuf enum <code>SEW_Story = 2;</code>
     */
    const SEW_Story = 2;
    /**
     * Generated from protobuf enum <code>SEW_Dungeon = 3;</code>
     */
    const SEW_Dungeon = 3;
    /**
     * Generated from protobuf enum <code>SEW_Infinite = 4;</code>
     */
    const SEW_Infinite = 4;
    /**
     * Generated from protobuf enum <code>SEW_Clan = 5;</code>
     */
    const SEW_Clan = 5;
    /**
     * Generated from protobuf enum <code>SEW_Arena = 6;</code>
     */
    const SEW_Arena = 6;
}

