<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgSetting.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgSetting</code>
 */
class MsgSetting extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgSetting.DataType type = 2;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>bool v_bool = 3;</code>
     */
    private $v_bool = false;
    /**
     * Generated from protobuf field <code>uint32 v_int = 4;</code>
     */
    private $v_int = 0;
    /**
     * Generated from protobuf field <code>float v_float = 5;</code>
     */
    private $v_float = 0.0;
    /**
     * Generated from protobuf field <code>fixed32 v_uid = 6;</code>
     */
    private $v_uid = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice v_price = 7;</code>
     */
    private $v_price = null;
    /**
     * Generated from protobuf field <code>string v_string = 8;</code>
     */
    private $v_string = '';
    /**
     * Generated from protobuf field <code>uint64 v_date = 9;</code>
     */
    private $v_date = 0;

    public function __construct() {
        \GPBMetadata\MsgSetting::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgSetting.DataType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgSetting.DataType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgSetting_DataType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool v_bool = 3;</code>
     * @return bool
     */
    public function getVBool()
    {
        return $this->v_bool;
    }

    /**
     * Generated from protobuf field <code>bool v_bool = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setVBool($var)
    {
        GPBUtil::checkBool($var);
        $this->v_bool = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 v_int = 4;</code>
     * @return int
     */
    public function getVInt()
    {
        return $this->v_int;
    }

    /**
     * Generated from protobuf field <code>uint32 v_int = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setVInt($var)
    {
        GPBUtil::checkUint32($var);
        $this->v_int = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float v_float = 5;</code>
     * @return float
     */
    public function getVFloat()
    {
        return $this->v_float;
    }

    /**
     * Generated from protobuf field <code>float v_float = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setVFloat($var)
    {
        GPBUtil::checkFloat($var);
        $this->v_float = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 v_uid = 6;</code>
     * @return int
     */
    public function getVUid()
    {
        return $this->v_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 v_uid = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setVUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->v_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice v_price = 7;</code>
     * @return \Msggamedata\MsgPrice
     */
    public function getVPrice()
    {
        return $this->v_price;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice v_price = 7;</code>
     * @param \Msggamedata\MsgPrice $var
     * @return $this
     */
    public function setVPrice($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgPrice::class);
        $this->v_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string v_string = 8;</code>
     * @return string
     */
    public function getVString()
    {
        return $this->v_string;
    }

    /**
     * Generated from protobuf field <code>string v_string = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setVString($var)
    {
        GPBUtil::checkString($var, True);
        $this->v_string = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 v_date = 9;</code>
     * @return int|string
     */
    public function getVDate()
    {
        return $this->v_date;
    }

    /**
     * Generated from protobuf field <code>uint64 v_date = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->v_date = $var;

        return $this;
    }

}

