<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgStageMonsterFestival.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgStageMonsterFestival</code>
 */
class MsgStageMonsterFestival extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 stage_monster_uid = 1;</code>
     */
    private $stage_monster_uid = 0;
    /**
     * Generated from protobuf field <code>uint32 difficulty = 2;</code>
     */
    private $difficulty = 0;
    /**
     * Generated from protobuf field <code>repeated fixed32 stage_uids = 3;</code>
     */
    private $stage_uids;
    /**
     * Generated from protobuf field <code>float prob = 4;</code>
     */
    private $prob = 0.0;

    public function __construct() {
        \GPBMetadata\MsgStageMonsterFestival::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 stage_monster_uid = 1;</code>
     * @return int
     */
    public function getStageMonsterUid()
    {
        return $this->stage_monster_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 stage_monster_uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStageMonsterUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->stage_monster_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 difficulty = 2;</code>
     * @return int
     */
    public function getDifficulty()
    {
        return $this->difficulty;
    }

    /**
     * Generated from protobuf field <code>uint32 difficulty = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDifficulty($var)
    {
        GPBUtil::checkUint32($var);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated fixed32 stage_uids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStageUids()
    {
        return $this->stage_uids;
    }

    /**
     * Generated from protobuf field <code>repeated fixed32 stage_uids = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStageUids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED32);
        $this->stage_uids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float prob = 4;</code>
     * @return float
     */
    public function getProb()
    {
        return $this->prob;
    }

    /**
     * Generated from protobuf field <code>float prob = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setProb($var)
    {
        GPBUtil::checkFloat($var);
        $this->prob = $var;

        return $this;
    }

}

