<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgShopItemMetaMonster.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgShopItemMetaMonster.MonsterPackage</code>
 */
class MsgShopItemMetaMonster_MonsterPackage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem general = 1;</code>
     */
    private $general = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem must = 2;</code>
     */
    private $must = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem bonus = 3;</code>
     */
    private $bonus = null;

    public function __construct() {
        \GPBMetadata\MsgShopItemMetaMonster::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem general = 1;</code>
     * @return \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem
     */
    public function getGeneral()
    {
        return $this->general;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem general = 1;</code>
     * @param \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem $var
     * @return $this
     */
    public function setGeneral($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem::class);
        $this->general = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem must = 2;</code>
     * @return \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem
     */
    public function getMust()
    {
        return $this->must;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem must = 2;</code>
     * @param \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem $var
     * @return $this
     */
    public function setMust($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem::class);
        $this->must = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem bonus = 3;</code>
     * @return \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem
     */
    public function getBonus()
    {
        return $this->bonus;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgShopItemMetaMonster.MonsterPackageItem bonus = 3;</code>
     * @param \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem $var
     * @return $this
     */
    public function setBonus($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgShopItemMetaMonster_MonsterPackageItem::class);
        $this->bonus = $var;

        return $this;
    }

}

