<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgStatusEffect.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MsgStatusEffect\StatusEffectSubType</code>
 */
class MsgStatusEffect_StatusEffectSubType
{
    /**
     * Generated from protobuf enum <code>StatusEffectSubTypeNULL = 0;</code>
     */
    const StatusEffectSubTypeNULL = 0;
    /**
     * Generated from protobuf enum <code>SEST_BuffAttack = 1;</code>
     */
    const SEST_BuffAttack = 1;
    /**
     * Generated from protobuf enum <code>SEST_BuffDefence = 2;</code>
     */
    const SEST_BuffDefence = 2;
    /**
     * Generated from protobuf enum <code>SEST_BuffHeal = 3;</code>
     */
    const SEST_BuffHeal = 3;
    /**
     * Generated from protobuf enum <code>SEST_BuffHpCrystalRecovery = 4;</code>
     */
    const SEST_BuffHpCrystalRecovery = 4;
    /**
     * Generated from protobuf enum <code>SEST_BuffMpCrystalRecovery = 5;</code>
     */
    const SEST_BuffMpCrystalRecovery = 5;
    /**
     * Generated from protobuf enum <code>SEST_BuffHpCrystalGetProb = 6;</code>
     */
    const SEST_BuffHpCrystalGetProb = 6;
    /**
     * Generated from protobuf enum <code>SEST_BuffMpCrystalGetProb = 7;</code>
     */
    const SEST_BuffMpCrystalGetProb = 7;
    /**
     * Generated from protobuf enum <code>SEST_BuffCriticalProb = 8;</code>
     */
    const SEST_BuffCriticalProb = 8;
    /**
     * Generated from protobuf enum <code>SEST_BuffCriticalDamage = 9;</code>
     */
    const SEST_BuffCriticalDamage = 9;
    /**
     * Generated from protobuf enum <code>SEST_BuffFinalValueHeal = 10;</code>
     */
    const SEST_BuffFinalValueHeal = 10;
    /**
     * Generated from protobuf enum <code>SEST_DebuffAttack = 21;</code>
     */
    const SEST_DebuffAttack = 21;
    /**
     * Generated from protobuf enum <code>SEST_DebuffDefence = 22;</code>
     */
    const SEST_DebuffDefence = 22;
    /**
     * Generated from protobuf enum <code>SEST_DebuffHeal = 23;</code>
     */
    const SEST_DebuffHeal = 23;
    /**
     * Generated from protobuf enum <code>SEST_DebuffHpCrystalRecovery = 24;</code>
     */
    const SEST_DebuffHpCrystalRecovery = 24;
    /**
     * Generated from protobuf enum <code>SEST_DebuffMpCrystalRecovery = 25;</code>
     */
    const SEST_DebuffMpCrystalRecovery = 25;
    /**
     * Generated from protobuf enum <code>SEST_DebuffHpCrystalGetProb = 26;</code>
     */
    const SEST_DebuffHpCrystalGetProb = 26;
    /**
     * Generated from protobuf enum <code>SEST_DebuffMpCrystalGetProb = 27;</code>
     */
    const SEST_DebuffMpCrystalGetProb = 27;
    /**
     * Generated from protobuf enum <code>SEST_DebuffAttackAndDefence = 28;</code>
     */
    const SEST_DebuffAttackAndDefence = 28;
    /**
     * Generated from protobuf enum <code>SEST_DebuffDefenceAndHeal = 29;</code>
     */
    const SEST_DebuffDefenceAndHeal = 29;
    /**
     * Generated from protobuf enum <code>SEST_DebuffAttackAndHeal = 30;</code>
     */
    const SEST_DebuffAttackAndHeal = 30;
    /**
     * Generated from protobuf enum <code>SEST_ClearBuff = 31;</code>
     */
    const SEST_ClearBuff = 31;
    /**
     * Generated from protobuf enum <code>SEST_ClearDebuff = 32;</code>
     */
    const SEST_ClearDebuff = 32;
    /**
     * Generated from protobuf enum <code>SEST_ClearShield = 33;</code>
     */
    const SEST_ClearShield = 33;
    /**
     * Generated from protobuf enum <code>SEST_OngoingIncHp = 41;</code>
     */
    const SEST_OngoingIncHp = 41;
    /**
     * Generated from protobuf enum <code>SEST_OngoingDecHp = 42;</code>
     */
    const SEST_OngoingDecHp = 42;
    /**
     * Generated from protobuf enum <code>SEST_OngoingIncMp = 43;</code>
     */
    const SEST_OngoingIncMp = 43;
    /**
     * Generated from protobuf enum <code>SEST_OngoingDecMp = 44;</code>
     */
    const SEST_OngoingDecMp = 44;
    /**
     * Generated from protobuf enum <code>SEST_OngoingDecHpPercentFromMaxHp = 45;</code>
     */
    const SEST_OngoingDecHpPercentFromMaxHp = 45;
    /**
     * Generated from protobuf enum <code>SEST_OngoingDecHpAbsolute = 46;</code>
     */
    const SEST_OngoingDecHpAbsolute = 46;
    /**
     * Generated from protobuf enum <code>SEST_OngoingDoubleDecHpPercentFromMaxHp = 47;</code>
     */
    const SEST_OngoingDoubleDecHpPercentFromMaxHp = 47;
    /**
     * Generated from protobuf enum <code>SEST_OngoingTripleDecHpPercentFromMaxHp = 48;</code>
     */
    const SEST_OngoingTripleDecHpPercentFromMaxHp = 48;
    /**
     * Generated from protobuf enum <code>SEST_OngoingWeakPoint = 49;</code>
     */
    const SEST_OngoingWeakPoint = 49;
    /**
     * Generated from protobuf enum <code>SEST_Stun = 51;</code>
     */
    const SEST_Stun = 51;
    /**
     * Generated from protobuf enum <code>SEST_StunElectricShock = 52;</code>
     */
    const SEST_StunElectricShock = 52;
    /**
     * Generated from protobuf enum <code>SEST_StunStone = 53;</code>
     */
    const SEST_StunStone = 53;
    /**
     * Generated from protobuf enum <code>SEST_StunSleep = 54;</code>
     */
    const SEST_StunSleep = 54;
    /**
     * Generated from protobuf enum <code>SEST_Silence = 61;</code>
     */
    const SEST_Silence = 61;
    /**
     * Generated from protobuf enum <code>SEST_HealMyHpByEnemyDamage = 71;</code>
     */
    const SEST_HealMyHpByEnemyDamage = 71;
    /**
     * Generated from protobuf enum <code>SEST_HealMyMpByEnemyDamage = 72;</code>
     */
    const SEST_HealMyMpByEnemyDamage = 72;
    /**
     * Generated from protobuf enum <code>SEST_RecoveryMyMpByMyDamage = 81;</code>
     */
    const SEST_RecoveryMyMpByMyDamage = 81;
    /**
     * Generated from protobuf enum <code>SEST_ShieldDamageByAbsolute = 91;</code>
     */
    const SEST_ShieldDamageByAbsolute = 91;
    /**
     * Generated from protobuf enum <code>SEST_ShieldDamageByMaxHp = 92;</code>
     */
    const SEST_ShieldDamageByMaxHp = 92;
    /**
     * Generated from protobuf enum <code>SEST_ShieldDamageByLev = 93;</code>
     */
    const SEST_ShieldDamageByLev = 93;
    /**
     * Generated from protobuf enum <code>SEST_DecEnemyMpByEnemyDamage = 101;</code>
     */
    const SEST_DecEnemyMpByEnemyDamage = 101;
    /**
     * Generated from protobuf enum <code>SEST_ProvokeMe = 111;</code>
     */
    const SEST_ProvokeMe = 111;
    /**
     * Generated from protobuf enum <code>SEST_BossImmuneStatusEffect = 121;</code>
     */
    const SEST_BossImmuneStatusEffect = 121;
    /**
     * Generated from protobuf enum <code>SEST_BossAddStatus = 122;</code>
     */
    const SEST_BossAddStatus = 122;
    /**
     * Generated from protobuf enum <code>SEST_BossHeal = 123;</code>
     */
    const SEST_BossHeal = 123;
    /**
     * Generated from protobuf enum <code>SEST_BossImmuneStatusEffectWithoutProvoke = 124;</code>
     */
    const SEST_BossImmuneStatusEffectWithoutProvoke = 124;
    /**
     * Generated from protobuf enum <code>SEST_BossImmuneStatusEffectWithOngoingDec = 125;</code>
     */
    const SEST_BossImmuneStatusEffectWithOngoingDec = 125;
    /**
     * Generated from protobuf enum <code>SEST_BossImmuneClanBoss = 126;</code>
     */
    const SEST_BossImmuneClanBoss = 126;
    /**
     * Generated from protobuf enum <code>SEST_BossImmuneClanBossWithoutOngoing = 127;</code>
     */
    const SEST_BossImmuneClanBossWithoutOngoing = 127;
    /**
     * Generated from protobuf enum <code>SEST_BossImmuneGolemBoss = 128;</code>
     */
    const SEST_BossImmuneGolemBoss = 128;
    /**
     * Generated from protobuf enum <code>SEST_BossAddStatusWithClearDebuff = 129;</code>
     */
    const SEST_BossAddStatusWithClearDebuff = 129;
    /**
     * Generated from protobuf enum <code>SEST_BossImmuneColossusBoss = 130;</code>
     */
    const SEST_BossImmuneColossusBoss = 130;
    /**
     * Generated from protobuf enum <code>SEST_BossReduceOngoingDecHp = 131;</code>
     */
    const SEST_BossReduceOngoingDecHp = 131;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffHp = 201;</code>
     */
    const SEST_LeaderBuffHp = 201;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffAttack = 202;</code>
     */
    const SEST_LeaderBuffAttack = 202;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffDefence = 203;</code>
     */
    const SEST_LeaderBuffDefence = 203;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffHeal = 204;</code>
     */
    const SEST_LeaderBuffHeal = 204;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffHpCrystalRecovery = 205;</code>
     */
    const SEST_LeaderBuffHpCrystalRecovery = 205;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffMpCrystalRecovery = 206;</code>
     */
    const SEST_LeaderBuffMpCrystalRecovery = 206;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffCriticalDamage = 207;</code>
     */
    const SEST_LeaderBuffCriticalDamage = 207;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffCriticalProb = 208;</code>
     */
    const SEST_LeaderBuffCriticalProb = 208;
    /**
     * Generated from protobuf enum <code>SEST_LeaderBuffStatusEffectResistance = 209;</code>
     */
    const SEST_LeaderBuffStatusEffectResistance = 209;
    /**
     * Generated from protobuf enum <code>SEST_LeaderDebuffAttackToEnemy = 210;</code>
     */
    const SEST_LeaderDebuffAttackToEnemy = 210;
    /**
     * Generated from protobuf enum <code>SEST_LeaderDebuffDefenceToEnemy = 211;</code>
     */
    const SEST_LeaderDebuffDefenceToEnemy = 211;
    /**
     * Generated from protobuf enum <code>SEST_LeaderDebuffHealToEnemy = 212;</code>
     */
    const SEST_LeaderDebuffHealToEnemy = 212;
    /**
     * Generated from protobuf enum <code>SEST_LeaderDebuffHpCrystalRecoveryToEnemy = 213;</code>
     */
    const SEST_LeaderDebuffHpCrystalRecoveryToEnemy = 213;
    /**
     * Generated from protobuf enum <code>SEST_LeaderDebuffMpCrystalRecoveryToEnemy = 214;</code>
     */
    const SEST_LeaderDebuffMpCrystalRecoveryToEnemy = 214;
    /**
     * Generated from protobuf enum <code>SEST_LeaderDebuffCriticalDamageToEnemy = 215;</code>
     */
    const SEST_LeaderDebuffCriticalDamageToEnemy = 215;
    /**
     * Generated from protobuf enum <code>SEST_LeaderDebuffCriticalProbToEnemy = 216;</code>
     */
    const SEST_LeaderDebuffCriticalProbToEnemy = 216;
    /**
     * Generated from protobuf enum <code>SEST_LeaderDebuffStatusEffectResistanceToEnemy = 217;</code>
     */
    const SEST_LeaderDebuffStatusEffectResistanceToEnemy = 217;
    /**
     * Generated from protobuf enum <code>SEST_SelfBuffCriticalProb = 301;</code>
     */
    const SEST_SelfBuffCriticalProb = 301;
    /**
     * Generated from protobuf enum <code>SEST_SelfBuffCriticalDamage = 302;</code>
     */
    const SEST_SelfBuffCriticalDamage = 302;
    /**
     * Generated from protobuf enum <code>SEST_SelfReplacedAttackByMaxHp = 303;</code>
     */
    const SEST_SelfReplacedAttackByMaxHp = 303;
    /**
     * Generated from protobuf enum <code>SEST_SelfReplacedAttackByMaxDefence = 304;</code>
     */
    const SEST_SelfReplacedAttackByMaxDefence = 304;
    /**
     * Generated from protobuf enum <code>SEST_SelfReplacedAttackByMaxHeal = 305;</code>
     */
    const SEST_SelfReplacedAttackByMaxHeal = 305;
    /**
     * Generated from protobuf enum <code>SEST_SelfAddDamageByElement = 306;</code>
     */
    const SEST_SelfAddDamageByElement = 306;
    /**
     * Generated from protobuf enum <code>SEST_SelfInvertSoulHptoMp = 307;</code>
     */
    const SEST_SelfInvertSoulHptoMp = 307;
    /**
     * Generated from protobuf enum <code>SEST_SelfInvertSoulMptoHp = 308;</code>
     */
    const SEST_SelfInvertSoulMptoHp = 308;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyMpByPercentFromMaxMp = 309;</code>
     */
    const SEST_SelfHealMyMpByPercentFromMaxMp = 309;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyMpByPercentFromMaxMpOurTeam = 310;</code>
     */
    const SEST_SelfHealMyMpByPercentFromMaxMpOurTeam = 310;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpByPercentFromMaxHp = 311;</code>
     */
    const SEST_SelfHealMyHpByPercentFromMaxHp = 311;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpByPercentFromMaxHpOurTeam = 312;</code>
     */
    const SEST_SelfHealMyHpByPercentFromMaxHpOurTeam = 312;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyMpByEnemyDamage = 313;</code>
     */
    const SEST_SelfHealMyMpByEnemyDamage = 313;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyMpByEnemyDamageOurTeam = 314;</code>
     */
    const SEST_SelfHealMyMpByEnemyDamageOurTeam = 314;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpByEnemyDamage = 315;</code>
     */
    const SEST_SelfHealMyHpByEnemyDamage = 315;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpByEnemyDamageOurTeam = 316;</code>
     */
    const SEST_SelfHealMyHpByEnemyDamageOurTeam = 316;
    /**
     * Generated from protobuf enum <code>SEST_SelfClearEnemyBuff = 317;</code>
     */
    const SEST_SelfClearEnemyBuff = 317;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpByPercentFromMyMaxHp = 318;</code>
     */
    const SEST_SelfHealMyHpByPercentFromMyMaxHp = 318;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpByPercentFromMyMaxHpOurTeam = 319;</code>
     */
    const SEST_SelfHealMyHpByPercentFromMyMaxHpOurTeam = 319;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyMpByPercentFromMyMaxMp = 320;</code>
     */
    const SEST_SelfHealMyMpByPercentFromMyMaxMp = 320;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyMpByPercentFromMyMaxMpOurTeam = 321;</code>
     */
    const SEST_SelfHealMyMpByPercentFromMyMaxMpOurTeam = 321;
    /**
     * Generated from protobuf enum <code>SEST_SelfCloneSoulHptoMp = 322;</code>
     */
    const SEST_SelfCloneSoulHptoMp = 322;
    /**
     * Generated from protobuf enum <code>SEST_SelfCloneSoulMptoHp = 323;</code>
     */
    const SEST_SelfCloneSoulMptoHp = 323;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpMpByPercentFromMyMaxHpMp = 324;</code>
     */
    const SEST_SelfHealMyHpMpByPercentFromMyMaxHpMp = 324;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpMpByPercentFromMyMaxHpMpOurTeam = 325;</code>
     */
    const SEST_SelfHealMyHpMpByPercentFromMyMaxHpMpOurTeam = 325;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyHpMpByPercentFromMaxHpMpOurTeam = 326;</code>
     */
    const SEST_SelfHealMyHpMpByPercentFromMaxHpMpOurTeam = 326;
    /**
     * Generated from protobuf enum <code>SEST_SelfAddDamageByAbsoluteElement = 327;</code>
     */
    const SEST_SelfAddDamageByAbsoluteElement = 327;
    /**
     * Generated from protobuf enum <code>SEST_SelfHealMyMpByPercentFromEnemyMp = 328;</code>
     */
    const SEST_SelfHealMyMpByPercentFromEnemyMp = 328;
    /**
     * Generated from protobuf enum <code>SEST_SelfAddDamageByEnemyMaxHp = 329;</code>
     */
    const SEST_SelfAddDamageByEnemyMaxHp = 329;
    /**
     * Generated from protobuf enum <code>SEST_SelfStealEnemyMp = 330;</code>
     */
    const SEST_SelfStealEnemyMp = 330;
    /**
     * Generated from protobuf enum <code>SEST_SelfStealEnemyMpByEnemyDamage = 331;</code>
     */
    const SEST_SelfStealEnemyMpByEnemyDamage = 331;
    /**
     * Generated from protobuf enum <code>SEST_SelfAddAttackByTurnAccumulate = 332;</code>
     */
    const SEST_SelfAddAttackByTurnAccumulate = 332;
    /**
     * Generated from protobuf enum <code>SEST_SelfAddAttackByHpLossRate = 333;</code>
     */
    const SEST_SelfAddAttackByHpLossRate = 333;
    /**
     * Generated from protobuf enum <code>SEST_SelfAddAttackByTargetDebuffCount = 334;</code>
     */
    const SEST_SelfAddAttackByTargetDebuffCount = 334;
    /**
     * Generated from protobuf enum <code>SEST_SealStatusEffect = 401;</code>
     */
    const SEST_SealStatusEffect = 401;
    /**
     * Generated from protobuf enum <code>SEST_DebuffCriticalProb = 1001;</code>
     */
    const SEST_DebuffCriticalProb = 1001;
    /**
     * Generated from protobuf enum <code>SEST_DebuffCriticalDamage = 1002;</code>
     */
    const SEST_DebuffCriticalDamage = 1002;
    /**
     * Generated from protobuf enum <code>SEST_DebuffFinalValueHeal = 1003;</code>
     */
    const SEST_DebuffFinalValueHeal = 1003;
    /**
     * Generated from protobuf enum <code>SEST_DebuffCriticalProbAndDamage = 1004;</code>
     */
    const SEST_DebuffCriticalProbAndDamage = 1004;
}

