<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgSanction.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgSanction</code>
 */
class MsgSanction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 sanction_idx = 1;</code>
     */
    private $sanction_idx = 0;
    /**
     * Generated from protobuf field <code>string sanction_type = 2;</code>
     */
    private $sanction_type = '';
    /**
     * Generated from protobuf field <code>uint64 account_idx = 3;</code>
     */
    private $account_idx = 0;
    /**
     * Generated from protobuf field <code>string target_key = 4;</code>
     */
    private $target_key = '';
    /**
     * Generated from protobuf field <code>uint64 s_date = 5;</code>
     */
    private $s_date = 0;
    /**
     * Generated from protobuf field <code>uint64 e_date = 6;</code>
     */
    private $e_date = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.UserAccountSanctionType reason_type = 7;</code>
     */
    private $reason_type = 0;
    /**
     * Generated from protobuf field <code>string subject = 8;</code>
     */
    private $subject = '';
    /**
     * Generated from protobuf field <code>string reason = 9;</code>
     */
    private $reason = '';
    /**
     * Generated from protobuf field <code>string memo = 10;</code>
     */
    private $memo = '';
    /**
     * Generated from protobuf field <code>uint64 reg_user = 11;</code>
     */
    private $reg_user = 0;
    /**
     * Generated from protobuf field <code>uint64 reg_date = 12;</code>
     */
    private $reg_date = 0;

    public function __construct() {
        \GPBMetadata\MsgSanction::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 sanction_idx = 1;</code>
     * @return int|string
     */
    public function getSanctionIdx()
    {
        return $this->sanction_idx;
    }

    /**
     * Generated from protobuf field <code>uint64 sanction_idx = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSanctionIdx($var)
    {
        GPBUtil::checkUint64($var);
        $this->sanction_idx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sanction_type = 2;</code>
     * @return string
     */
    public function getSanctionType()
    {
        return $this->sanction_type;
    }

    /**
     * Generated from protobuf field <code>string sanction_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSanctionType($var)
    {
        GPBUtil::checkString($var, True);
        $this->sanction_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 account_idx = 3;</code>
     * @return int|string
     */
    public function getAccountIdx()
    {
        return $this->account_idx;
    }

    /**
     * Generated from protobuf field <code>uint64 account_idx = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAccountIdx($var)
    {
        GPBUtil::checkUint64($var);
        $this->account_idx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_key = 4;</code>
     * @return string
     */
    public function getTargetKey()
    {
        return $this->target_key;
    }

    /**
     * Generated from protobuf field <code>string target_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 s_date = 5;</code>
     * @return int|string
     */
    public function getSDate()
    {
        return $this->s_date;
    }

    /**
     * Generated from protobuf field <code>uint64 s_date = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->s_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 e_date = 6;</code>
     * @return int|string
     */
    public function getEDate()
    {
        return $this->e_date;
    }

    /**
     * Generated from protobuf field <code>uint64 e_date = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->e_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.UserAccountSanctionType reason_type = 7;</code>
     * @return int
     */
    public function getReasonType()
    {
        return $this->reason_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.UserAccountSanctionType reason_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setReasonType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\UserAccountSanctionType::class);
        $this->reason_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject = 8;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>string subject = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reason = 9;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string memo = 10;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     * Generated from protobuf field <code>string memo = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 reg_user = 11;</code>
     * @return int|string
     */
    public function getRegUser()
    {
        return $this->reg_user;
    }

    /**
     * Generated from protobuf field <code>uint64 reg_user = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegUser($var)
    {
        GPBUtil::checkUint64($var);
        $this->reg_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 reg_date = 12;</code>
     * @return int|string
     */
    public function getRegDate()
    {
        return $this->reg_date;
    }

    /**
     * Generated from protobuf field <code>uint64 reg_date = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->reg_date = $var;

        return $this;
    }

}

