<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserClanMonsterSlotList.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgUserClanMonsterSlotList</code>
 */
class MsgUserClanMonsterSlotList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 indice = 1;</code>
     */
    private $indice;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserClanMonsterSlot monster_slots = 2;</code>
     */
    private $monster_slots;
    /**
     * Generated from protobuf field <code>repeated uint64 used_monsters = 3;</code>
     */
    private $used_monsters;

    public function __construct() {
        \GPBMetadata\MsgUserClanMonsterSlotList::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated uint32 indice = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndice()
    {
        return $this->indice;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 indice = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndice($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->indice = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserClanMonsterSlot monster_slots = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMonsterSlots()
    {
        return $this->monster_slots;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserClanMonsterSlot monster_slots = 2;</code>
     * @param \Msggamedata\MsgUserClanMonsterSlot[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMonsterSlots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgUserClanMonsterSlot::class);
        $this->monster_slots = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 used_monsters = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsedMonsters()
    {
        return $this->used_monsters;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 used_monsters = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsedMonsters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->used_monsters = $arr;

        return $this;
    }

}

