<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUIShortcut.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\MsgUIShortcut\ShopPlace</code>
 */
class MsgUIShortcut_ShopPlace
{
    /**
     * Generated from protobuf enum <code>ShopPlaceNULL = 0;</code>
     */
    const ShopPlaceNULL = 0;
    /**
     * Generated from protobuf enum <code>SP_Package = 1;</code>
     */
    const SP_Package = 1;
    /**
     * Generated from protobuf enum <code>SP_Costume = 2;</code>
     */
    const SP_Costume = 2;
}

