<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserMonthlyMonster.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgUserMonthlyMonster</code>
 */
class MsgUserMonthlyMonster extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 monthly_monster_season_idx = 1;</code>
     */
    private $monthly_monster_season_idx = 0;
    /**
     * Generated from protobuf field <code>uint64 user_id = 2;</code>
     */
    private $user_id = 0;
    /**
     * Generated from protobuf field <code>uint32 completed_quest_count = 3;</code>
     */
    private $completed_quest_count = 0;
    /**
     * Generated from protobuf field <code>uint32 rewarded_quest_count = 4;</code>
     */
    private $rewarded_quest_count = 0;

    public function __construct() {
        \GPBMetadata\MsgUserMonthlyMonster::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 monthly_monster_season_idx = 1;</code>
     * @return int
     */
    public function getMonthlyMonsterSeasonIdx()
    {
        return $this->monthly_monster_season_idx;
    }

    /**
     * Generated from protobuf field <code>uint32 monthly_monster_season_idx = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMonthlyMonsterSeasonIdx($var)
    {
        GPBUtil::checkUint32($var);
        $this->monthly_monster_season_idx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 completed_quest_count = 3;</code>
     * @return int
     */
    public function getCompletedQuestCount()
    {
        return $this->completed_quest_count;
    }

    /**
     * Generated from protobuf field <code>uint32 completed_quest_count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCompletedQuestCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->completed_quest_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 rewarded_quest_count = 4;</code>
     * @return int
     */
    public function getRewardedQuestCount()
    {
        return $this->rewarded_quest_count;
    }

    /**
     * Generated from protobuf field <code>uint32 rewarded_quest_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRewardedQuestCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->rewarded_quest_count = $var;

        return $this;
    }

}

