<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUIShortcut.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgUIShortcut</code>
 */
class MsgUIShortcut extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut.Place place = 1;</code>
     */
    private $place = 0;
    /**
     * Generated from protobuf field <code>fixed32 uid = 2;</code>
     */
    private $uid = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut.ShopPlace shop_place = 3;</code>
     */
    private $shop_place = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.StageDifficultyType stage_difficulty_type = 4;</code>
     */
    private $stage_difficulty_type = 0;

    public function __construct() {
        \GPBMetadata\MsgUIShortcut::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut.Place place = 1;</code>
     * @return int
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut.Place place = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPlace($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgUIShortcut_Place::class);
        $this->place = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 2;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 uid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut.ShopPlace shop_place = 3;</code>
     * @return int
     */
    public function getShopPlace()
    {
        return $this->shop_place;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUIShortcut.ShopPlace shop_place = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setShopPlace($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgUIShortcut_ShopPlace::class);
        $this->shop_place = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.StageDifficultyType stage_difficulty_type = 4;</code>
     * @return int
     */
    public function getStageDifficultyType()
    {
        return $this->stage_difficulty_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.StageDifficultyType stage_difficulty_type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStageDifficultyType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\StageDifficultyType::class);
        $this->stage_difficulty_type = $var;

        return $this;
    }

}

