<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgUserGift.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.MsgUserGift</code>
 */
class MsgUserGift extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>fixed32 sender_id = 2;</code>
     */
    private $sender_id = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.GiftSenderType sender_type = 3;</code>
     */
    private $sender_type = 0;
    /**
     * Generated from protobuf field <code>fixed32 msg_template = 4;</code>
     */
    private $msg_template = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.GiftType gift_type = 5;</code>
     */
    private $gift_type = 0;
    /**
     * Generated from protobuf field <code>fixed32 gift_uid = 6;</code>
     */
    private $gift_uid = 0;
    /**
     * Generated from protobuf field <code>uint32 gift_amount = 7;</code>
     */
    private $gift_amount = 0;
    /**
     * Generated from protobuf field <code>uint64 expire_date = 8;</code>
     */
    private $expire_date = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.MsgUserGiftInstantMonsterMeta instant_monster_meta = 9;</code>
     */
    private $instant_monster_meta = null;
    /**
     * Generated from protobuf field <code>string custom_msg = 10;</code>
     */
    private $custom_msg = '';
    /**
     * Generated from protobuf field <code>fixed32 promise_uid = 11;</code>
     */
    private $promise_uid = 0;

    public function __construct() {
        \GPBMetadata\MsgUserGift::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 sender_id = 2;</code>
     * @return int
     */
    public function getSenderId()
    {
        return $this->sender_id;
    }

    /**
     * Generated from protobuf field <code>fixed32 sender_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSenderId($var)
    {
        GPBUtil::checkUint32($var);
        $this->sender_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.GiftSenderType sender_type = 3;</code>
     * @return int
     */
    public function getSenderType()
    {
        return $this->sender_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.GiftSenderType sender_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSenderType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgUserGift_GiftSenderType::class);
        $this->sender_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 msg_template = 4;</code>
     * @return int
     */
    public function getMsgTemplate()
    {
        return $this->msg_template;
    }

    /**
     * Generated from protobuf field <code>fixed32 msg_template = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgTemplate($var)
    {
        GPBUtil::checkUint32($var);
        $this->msg_template = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.GiftType gift_type = 5;</code>
     * @return int
     */
    public function getGiftType()
    {
        return $this->gift_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.GiftType gift_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setGiftType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\MsgUserGift_GiftType::class);
        $this->gift_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 gift_uid = 6;</code>
     * @return int
     */
    public function getGiftUid()
    {
        return $this->gift_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 gift_uid = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setGiftUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->gift_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 gift_amount = 7;</code>
     * @return int
     */
    public function getGiftAmount()
    {
        return $this->gift_amount;
    }

    /**
     * Generated from protobuf field <code>uint32 gift_amount = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setGiftAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->gift_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expire_date = 8;</code>
     * @return int|string
     */
    public function getExpireDate()
    {
        return $this->expire_date;
    }

    /**
     * Generated from protobuf field <code>uint64 expire_date = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->expire_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.MsgUserGiftInstantMonsterMeta instant_monster_meta = 9;</code>
     * @return \Msggamedata\MsgUserGift_MsgUserGiftInstantMonsterMeta
     */
    public function getInstantMonsterMeta()
    {
        return $this->instant_monster_meta;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserGift.MsgUserGiftInstantMonsterMeta instant_monster_meta = 9;</code>
     * @param \Msggamedata\MsgUserGift_MsgUserGiftInstantMonsterMeta $var
     * @return $this
     */
    public function setInstantMonsterMeta($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserGift_MsgUserGiftInstantMonsterMeta::class);
        $this->instant_monster_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string custom_msg = 10;</code>
     * @return string
     */
    public function getCustomMsg()
    {
        return $this->custom_msg;
    }

    /**
     * Generated from protobuf field <code>string custom_msg = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->custom_msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 promise_uid = 11;</code>
     * @return int
     */
    public function getPromiseUid()
    {
        return $this->promise_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 promise_uid = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setPromiseUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->promise_uid = $var;

        return $this;
    }

}

