<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PurchaseCurrencyType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\PurchaseCurrencyType</code>
 */
class PurchaseCurrencyType
{
    /**
     * Generated from protobuf enum <code>PurchaseCurrencyTypeNULL = 0;</code>
     */
    const PurchaseCurrencyTypeNULL = 0;
    /**
     * Generated from protobuf enum <code>PCT_USD = 1;</code>
     */
    const PCT_USD = 1;
    /**
     * Generated from protobuf enum <code>PCT_KRW = 2;</code>
     */
    const PCT_KRW = 2;
    /**
     * Generated from protobuf enum <code>PCT_ETC = 3;</code>
     */
    const PCT_ETC = 3;
}

