<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqArenaBattleHistories.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqArenaBattleHistories</code>
 */
class ReqArenaBattleHistories extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\ReqArenaBattleHistories::initOnce();
        parent::__construct();
    }

}

