<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqCVCCandidateList.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqCVCCandidateList</code>
 */
class ReqCVCCandidateList extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\ReqCVCCandidateList::initOnce();
        parent::__construct();
    }

}

