<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqChangeHelloMessage.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqChangeHelloMessage</code>
 */
class ReqChangeHelloMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string msg = 1;</code>
     */
    private $msg = '';

    public function __construct() {
        \GPBMetadata\ReqChangeHelloMessage::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string msg = 1;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

