<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqLightContractBonus.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqLightContractBonus</code>
 */
class ReqLightContractBonus extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\ReqLightContractBonus::initOnce();
        parent::__construct();
    }

}

