<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqMonsterSummonByEgg.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqMonsterSummonByEgg</code>
 */
class ReqMonsterSummonByEgg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 item_uid = 1;</code>
     */
    private $item_uid = 0;
    /**
     * Generated from protobuf field <code>bool multiple_summon = 2;</code>
     */
    private $multiple_summon = false;

    public function __construct() {
        \GPBMetadata\ReqMonsterSummonByEgg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>fixed32 item_uid = 1;</code>
     * @return int
     */
    public function getItemUid()
    {
        return $this->item_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 item_uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setItemUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->item_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool multiple_summon = 2;</code>
     * @return bool
     */
    public function getMultipleSummon()
    {
        return $this->multiple_summon;
    }

    /**
     * Generated from protobuf field <code>bool multiple_summon = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setMultipleSummon($var)
    {
        GPBUtil::checkBool($var);
        $this->multiple_summon = $var;

        return $this;
    }

}

