<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqPushSetting.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqPushSetting</code>
 */
class ReqPushSetting extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.AccountPushSetting push_alarm = 1;</code>
     */
    private $push_alarm = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.AccountOSType os = 2;</code>
     */
    private $os = 0;
    /**
     * Generated from protobuf field <code>string push_token = 3;</code>
     */
    private $push_token = '';

    public function __construct() {
        \GPBMetadata\ReqPushSetting::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.AccountPushSetting push_alarm = 1;</code>
     * @return int
     */
    public function getPushAlarm()
    {
        return $this->push_alarm;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.AccountPushSetting push_alarm = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPushAlarm($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\AccountPushSetting::class);
        $this->push_alarm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.AccountOSType os = 2;</code>
     * @return int
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.AccountOSType os = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOs($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\AccountOSType::class);
        $this->os = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string push_token = 3;</code>
     * @return string
     */
    public function getPushToken()
    {
        return $this->push_token;
    }

    /**
     * Generated from protobuf field <code>string push_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPushToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_token = $var;

        return $this;
    }

}

