<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqRefreshClanMembers.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqRefreshClanMembers</code>
 */
class ReqRefreshClanMembers extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\ReqRefreshClanMembers::initOnce();
        parent::__construct();
    }

}

