<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSNSLogin.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\ReqSNSLogin\Option</code>
 */
class ReqSNSLogin_Option
{
    /**
     * Generated from protobuf enum <code>None = 0;</code>
     */
    const None = 0;
    /**
     * Generated from protobuf enum <code>UseCurrentData = 1;</code>
     */
    const UseCurrentData = 1;
    /**
     * Generated from protobuf enum <code>UseSNSData = 2;</code>
     */
    const UseSNSData = 2;
}

