<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUserApplyList.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqUserApplyList</code>
 */
class ReqUserApplyList extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\ReqUserApplyList::initOnce();
        parent::__construct();
    }

}

