<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqWarmUpMonsterEvolution.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.ReqWarmUpMonsterEvolution</code>
 */
class ReqWarmUpMonsterEvolution extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 base_user_monster_id = 1;</code>
     */
    private $base_user_monster_id = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 material_user_monster_ids = 2;</code>
     */
    private $material_user_monster_ids;

    public function __construct() {
        \GPBMetadata\ReqWarmUpMonsterEvolution::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 base_user_monster_id = 1;</code>
     * @return int|string
     */
    public function getBaseUserMonsterId()
    {
        return $this->base_user_monster_id;
    }

    /**
     * Generated from protobuf field <code>uint64 base_user_monster_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBaseUserMonsterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->base_user_monster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 material_user_monster_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMaterialUserMonsterIds()
    {
        return $this->material_user_monster_ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 material_user_monster_ids = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMaterialUserMonsterIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->material_user_monster_ids = $arr;

        return $this;
    }

}

