<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RewardGrade.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\RewardGrade</code>
 */
class RewardGrade
{
    /**
     * Generated from protobuf enum <code>RewardGradeNULL = 0;</code>
     */
    const RewardGradeNULL = 0;
    /**
     * Generated from protobuf enum <code>RG_Normal = 1;</code>
     */
    const RG_Normal = 1;
    /**
     * Generated from protobuf enum <code>RG_Rare = 2;</code>
     */
    const RG_Rare = 2;
    /**
     * Generated from protobuf enum <code>RG_SuperRare = 3;</code>
     */
    const RG_SuperRare = 3;
}

