<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspApplyClanWar.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspApplyClanWar</code>
 */
class RspApplyClanWar extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\RspApplyClanWar::initOnce();
        parent::__construct();
    }

}

