<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspBuyMonsterCostumeBundle.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspBuyMonsterCostumeBundle</code>
 */
class RspBuyMonsterCostumeBundle extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     */
    private $user = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterCostumeBundle monster_costume_bundle = 2;</code>
     */
    private $monster_costume_bundle = null;

    public function __construct() {
        \GPBMetadata\RspBuyMonsterCostumeBundle::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     * @return \Msggamedata\MsgUser
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     * @param \Msggamedata\MsgUser $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUser::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterCostumeBundle monster_costume_bundle = 2;</code>
     * @return \Msggamedata\MsgUserMonsterCostumeBundle
     */
    public function getMonsterCostumeBundle()
    {
        return $this->monster_costume_bundle;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterCostumeBundle monster_costume_bundle = 2;</code>
     * @param \Msggamedata\MsgUserMonsterCostumeBundle $var
     * @return $this
     */
    public function setMonsterCostumeBundle($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonsterCostumeBundle::class);
        $this->monster_costume_bundle = $var;

        return $this;
    }

}

