<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspBattleEnd.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspBattleEnd</code>
 */
class RspBattleEnd extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.BattleType battle_type = 1;</code>
     */
    private $battle_type = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgRunningServerEvent apply_event_list = 2;</code>
     */
    private $apply_event_list;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndScenario scenario = 3;</code>
     */
    private $scenario = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndDungeon dungeon = 4;</code>
     */
    private $dungeon = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndFriendDungeon friend_dungeon = 5;</code>
     */
    private $friend_dungeon = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndArena arena = 6;</code>
     */
    private $arena = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndInfinite infinite = 7;</code>
     */
    private $infinite = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndClan clan = 8;</code>
     */
    private $clan = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndCVC cvc = 9;</code>
     */
    private $cvc = null;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserBooster apply_booster_list = 10;</code>
     */
    private $apply_booster_list;

    public function __construct() {
        \GPBMetadata\RspBattleEnd::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.BattleType battle_type = 1;</code>
     * @return int
     */
    public function getBattleType()
    {
        return $this->battle_type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.BattleType battle_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBattleType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\BattleType::class);
        $this->battle_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgRunningServerEvent apply_event_list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApplyEventList()
    {
        return $this->apply_event_list;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgRunningServerEvent apply_event_list = 2;</code>
     * @param \Msggamedata\MsgRunningServerEvent[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApplyEventList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgRunningServerEvent::class);
        $this->apply_event_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndScenario scenario = 3;</code>
     * @return \Msggamedata\MsgRspBattleEndScenario
     */
    public function getScenario()
    {
        return $this->scenario;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndScenario scenario = 3;</code>
     * @param \Msggamedata\MsgRspBattleEndScenario $var
     * @return $this
     */
    public function setScenario($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgRspBattleEndScenario::class);
        $this->scenario = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndDungeon dungeon = 4;</code>
     * @return \Msggamedata\MsgRspBattleEndDungeon
     */
    public function getDungeon()
    {
        return $this->dungeon;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndDungeon dungeon = 4;</code>
     * @param \Msggamedata\MsgRspBattleEndDungeon $var
     * @return $this
     */
    public function setDungeon($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgRspBattleEndDungeon::class);
        $this->dungeon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndFriendDungeon friend_dungeon = 5;</code>
     * @return \Msggamedata\MsgRspBattleEndFriendDungeon
     */
    public function getFriendDungeon()
    {
        return $this->friend_dungeon;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndFriendDungeon friend_dungeon = 5;</code>
     * @param \Msggamedata\MsgRspBattleEndFriendDungeon $var
     * @return $this
     */
    public function setFriendDungeon($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgRspBattleEndFriendDungeon::class);
        $this->friend_dungeon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndArena arena = 6;</code>
     * @return \Msggamedata\MsgRspBattleEndArena
     */
    public function getArena()
    {
        return $this->arena;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndArena arena = 6;</code>
     * @param \Msggamedata\MsgRspBattleEndArena $var
     * @return $this
     */
    public function setArena($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgRspBattleEndArena::class);
        $this->arena = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndInfinite infinite = 7;</code>
     * @return \Msggamedata\MsgRspBattleEndInfinite
     */
    public function getInfinite()
    {
        return $this->infinite;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndInfinite infinite = 7;</code>
     * @param \Msggamedata\MsgRspBattleEndInfinite $var
     * @return $this
     */
    public function setInfinite($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgRspBattleEndInfinite::class);
        $this->infinite = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndClan clan = 8;</code>
     * @return \Msggamedata\MsgRspBattleEndClan
     */
    public function getClan()
    {
        return $this->clan;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndClan clan = 8;</code>
     * @param \Msggamedata\MsgRspBattleEndClan $var
     * @return $this
     */
    public function setClan($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgRspBattleEndClan::class);
        $this->clan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndCVC cvc = 9;</code>
     * @return \Msggamedata\MsgRspBattleEndCVC
     */
    public function getCvc()
    {
        return $this->cvc;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgRspBattleEndCVC cvc = 9;</code>
     * @param \Msggamedata\MsgRspBattleEndCVC $var
     * @return $this
     */
    public function setCvc($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgRspBattleEndCVC::class);
        $this->cvc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserBooster apply_booster_list = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApplyBoosterList()
    {
        return $this->apply_booster_list;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserBooster apply_booster_list = 10;</code>
     * @param \Msggamedata\MsgUserBooster[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApplyBoosterList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgUserBooster::class);
        $this->apply_booster_list = $arr;

        return $this;
    }

}

