<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspCombineBeyondStone.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspCombineBeyondStone</code>
 */
class RspCombineBeyondStone extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem user_item_source = 1;</code>
     */
    private $user_item_source = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem user_item_dest = 2;</code>
     */
    private $user_item_dest = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 3;</code>
     */
    private $user = null;

    public function __construct() {
        \GPBMetadata\RspCombineBeyondStone::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem user_item_source = 1;</code>
     * @return \Msggamedata\MsgUserItem
     */
    public function getUserItemSource()
    {
        return $this->user_item_source;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem user_item_source = 1;</code>
     * @param \Msggamedata\MsgUserItem $var
     * @return $this
     */
    public function setUserItemSource($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserItem::class);
        $this->user_item_source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem user_item_dest = 2;</code>
     * @return \Msggamedata\MsgUserItem
     */
    public function getUserItemDest()
    {
        return $this->user_item_dest;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserItem user_item_dest = 2;</code>
     * @param \Msggamedata\MsgUserItem $var
     * @return $this
     */
    public function setUserItemDest($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserItem::class);
        $this->user_item_dest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 3;</code>
     * @return \Msggamedata\MsgUser
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 3;</code>
     * @param \Msggamedata\MsgUser $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUser::class);
        $this->user = $var;

        return $this;
    }

}

