<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspChangeClanMemberGrade.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspChangeClanMemberGrade</code>
 */
class RspChangeClanMemberGrade extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     */
    private $user_id = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.ClanMemberGrade member_grade = 2;</code>
     */
    private $member_grade = 0;

    public function __construct() {
        \GPBMetadata\RspChangeClanMemberGrade::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.ClanMemberGrade member_grade = 2;</code>
     * @return int
     */
    public function getMemberGrade()
    {
        return $this->member_grade;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.ClanMemberGrade member_grade = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberGrade($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\ClanMemberGrade::class);
        $this->member_grade = $var;

        return $this;
    }

}

