<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspFriendBonus.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspFriendBonus</code>
 */
class RspFriendBonus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 friend_user_id = 1;</code>
     */
    private $friend_user_id = 0;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 2;</code>
     */
    private $user = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice reward = 3;</code>
     */
    private $reward = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgFriend friend = 4;</code>
     */
    private $friend = null;

    public function __construct() {
        \GPBMetadata\RspFriendBonus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 friend_user_id = 1;</code>
     * @return int|string
     */
    public function getFriendUserId()
    {
        return $this->friend_user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 friend_user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFriendUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->friend_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 2;</code>
     * @return \Msggamedata\MsgUser
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 2;</code>
     * @param \Msggamedata\MsgUser $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUser::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice reward = 3;</code>
     * @return \Msggamedata\MsgPrice
     */
    public function getReward()
    {
        return $this->reward;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgPrice reward = 3;</code>
     * @param \Msggamedata\MsgPrice $var
     * @return $this
     */
    public function setReward($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgPrice::class);
        $this->reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgFriend friend = 4;</code>
     * @return \Msggamedata\MsgFriend
     */
    public function getFriend()
    {
        return $this->friend;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgFriend friend = 4;</code>
     * @param \Msggamedata\MsgFriend $var
     * @return $this
     */
    public function setFriend($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgFriend::class);
        $this->friend = $var;

        return $this;
    }

}

