<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspGetClanReward.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspGetClanReward</code>
 */
class RspGetClanReward extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 boss_level = 1;</code>
     */
    private $boss_level = 0;
    /**
     * Generated from protobuf field <code>uint32 grade = 2;</code>
     */
    private $grade = 0;
    /**
     * Generated from protobuf field <code>uint32 cvc_rank = 3;</code>
     */
    private $cvc_rank = 0;
    /**
     * Generated from protobuf field <code>uint32 cvc_grade = 4;</code>
     */
    private $cvc_grade = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserGift cve_user_gifts = 5;</code>
     */
    private $cve_user_gifts;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserGift cvc_user_gifts = 6;</code>
     */
    private $cvc_user_gifts;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserClanMember user_clan_member = 7;</code>
     */
    private $user_clan_member = null;
    /**
     * Generated from protobuf field <code>uint32 soulstone_uid = 8;</code>
     */
    private $soulstone_uid = 0;

    public function __construct() {
        \GPBMetadata\RspGetClanReward::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 boss_level = 1;</code>
     * @return int
     */
    public function getBossLevel()
    {
        return $this->boss_level;
    }

    /**
     * Generated from protobuf field <code>uint32 boss_level = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBossLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->boss_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 grade = 2;</code>
     * @return int
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     * Generated from protobuf field <code>uint32 grade = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkUint32($var);
        $this->grade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cvc_rank = 3;</code>
     * @return int
     */
    public function getCvcRank()
    {
        return $this->cvc_rank;
    }

    /**
     * Generated from protobuf field <code>uint32 cvc_rank = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCvcRank($var)
    {
        GPBUtil::checkUint32($var);
        $this->cvc_rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cvc_grade = 4;</code>
     * @return int
     */
    public function getCvcGrade()
    {
        return $this->cvc_grade;
    }

    /**
     * Generated from protobuf field <code>uint32 cvc_grade = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCvcGrade($var)
    {
        GPBUtil::checkUint32($var);
        $this->cvc_grade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserGift cve_user_gifts = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCveUserGifts()
    {
        return $this->cve_user_gifts;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserGift cve_user_gifts = 5;</code>
     * @param \Msggamedata\MsgUserGift[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCveUserGifts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgUserGift::class);
        $this->cve_user_gifts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserGift cvc_user_gifts = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCvcUserGifts()
    {
        return $this->cvc_user_gifts;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserGift cvc_user_gifts = 6;</code>
     * @param \Msggamedata\MsgUserGift[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCvcUserGifts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgUserGift::class);
        $this->cvc_user_gifts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserClanMember user_clan_member = 7;</code>
     * @return \Msggamedata\MsgUserClanMember
     */
    public function getUserClanMember()
    {
        return $this->user_clan_member;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserClanMember user_clan_member = 7;</code>
     * @param \Msggamedata\MsgUserClanMember $var
     * @return $this
     */
    public function setUserClanMember($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserClanMember::class);
        $this->user_clan_member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 soulstone_uid = 8;</code>
     * @return int
     */
    public function getSoulstoneUid()
    {
        return $this->soulstone_uid;
    }

    /**
     * Generated from protobuf field <code>uint32 soulstone_uid = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setSoulstoneUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->soulstone_uid = $var;

        return $this;
    }

}

