<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspMonsterSummonByRevive.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspMonsterSummonByRevive</code>
 */
class RspMonsterSummonByRevive extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     */
    private $user = null;
    /**
     * Generated from protobuf field <code>fixed32 revive_uid = 2;</code>
     */
    private $revive_uid = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 resource_monsters = 3;</code>
     */
    private $resource_monsters;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster result_monster = 4;</code>
     */
    private $result_monster = null;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserMonsterDictData user_monster_dict_data = 5;</code>
     */
    private $user_monster_dict_data;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster reward_monster = 6;</code>
     */
    private $reward_monster = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster reward_special_monster = 7;</code>
     */
    private $reward_special_monster = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgReviveMonsterData revive_monster_data = 8;</code>
     */
    private $revive_monster_data = null;

    public function __construct() {
        \GPBMetadata\RspMonsterSummonByRevive::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     * @return \Msggamedata\MsgUser
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     * @param \Msggamedata\MsgUser $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUser::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 revive_uid = 2;</code>
     * @return int
     */
    public function getReviveUid()
    {
        return $this->revive_uid;
    }

    /**
     * Generated from protobuf field <code>fixed32 revive_uid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setReviveUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->revive_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 resource_monsters = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResourceMonsters()
    {
        return $this->resource_monsters;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 resource_monsters = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResourceMonsters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->resource_monsters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster result_monster = 4;</code>
     * @return \Msggamedata\MsgUserMonster
     */
    public function getResultMonster()
    {
        return $this->result_monster;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster result_monster = 4;</code>
     * @param \Msggamedata\MsgUserMonster $var
     * @return $this
     */
    public function setResultMonster($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonster::class);
        $this->result_monster = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserMonsterDictData user_monster_dict_data = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserMonsterDictData()
    {
        return $this->user_monster_dict_data;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserMonsterDictData user_monster_dict_data = 5;</code>
     * @param \Msggamedata\MsgUserMonsterDictData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserMonsterDictData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgUserMonsterDictData::class);
        $this->user_monster_dict_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster reward_monster = 6;</code>
     * @return \Msggamedata\MsgUserMonster
     */
    public function getRewardMonster()
    {
        return $this->reward_monster;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster reward_monster = 6;</code>
     * @param \Msggamedata\MsgUserMonster $var
     * @return $this
     */
    public function setRewardMonster($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonster::class);
        $this->reward_monster = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster reward_special_monster = 7;</code>
     * @return \Msggamedata\MsgUserMonster
     */
    public function getRewardSpecialMonster()
    {
        return $this->reward_special_monster;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster reward_special_monster = 7;</code>
     * @param \Msggamedata\MsgUserMonster $var
     * @return $this
     */
    public function setRewardSpecialMonster($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonster::class);
        $this->reward_special_monster = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgReviveMonsterData revive_monster_data = 8;</code>
     * @return \Msggamedata\MsgReviveMonsterData
     */
    public function getReviveMonsterData()
    {
        return $this->revive_monster_data;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgReviveMonsterData revive_monster_data = 8;</code>
     * @param \Msggamedata\MsgReviveMonsterData $var
     * @return $this
     */
    public function setReviveMonsterData($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgReviveMonsterData::class);
        $this->revive_monster_data = $var;

        return $this;
    }

}

