<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspMonsterSummonBySoulstone.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspMonsterSummonBySoulstone</code>
 */
class RspMonsterSummonBySoulstone extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     */
    private $user = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster user_monster = 2;</code>
     */
    private $user_monster = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterDictData user_monster_dict_data = 3;</code>
     */
    private $user_monster_dict_data = null;

    public function __construct() {
        \GPBMetadata\RspMonsterSummonBySoulstone::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     * @return \Msggamedata\MsgUser
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUser user = 1;</code>
     * @param \Msggamedata\MsgUser $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUser::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster user_monster = 2;</code>
     * @return \Msggamedata\MsgUserMonster
     */
    public function getUserMonster()
    {
        return $this->user_monster;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonster user_monster = 2;</code>
     * @param \Msggamedata\MsgUserMonster $var
     * @return $this
     */
    public function setUserMonster($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonster::class);
        $this->user_monster = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterDictData user_monster_dict_data = 3;</code>
     * @return \Msggamedata\MsgUserMonsterDictData
     */
    public function getUserMonsterDictData()
    {
        return $this->user_monster_dict_data;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMonsterDictData user_monster_dict_data = 3;</code>
     * @param \Msggamedata\MsgUserMonsterDictData $var
     * @return $this
     */
    public function setUserMonsterDictData($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMonsterDictData::class);
        $this->user_monster_dict_data = $var;

        return $this;
    }

}

