<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspRefreshDungeonHistory.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspRefreshDungeonHistory</code>
 */
class RspRefreshDungeonHistory extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.RefreshDungeonType type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserDungeonStageHistory user_dungeon_stage_history = 2;</code>
     */
    private $user_dungeon_stage_history;
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgFriendDungeonFindHistory friend_dungeons = 3;</code>
     */
    private $friend_dungeons;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgInfiniteDungeonHistory infinite_dungeon = 4;</code>
     */
    private $infinite_dungeon = null;
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 5;</code>
     */
    private $colossus_stage_history = null;

    public function __construct() {
        \GPBMetadata\RspRefreshDungeonHistory::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.RefreshDungeonType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.RefreshDungeonType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Msggamedata\RefreshDungeonType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserDungeonStageHistory user_dungeon_stage_history = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserDungeonStageHistory()
    {
        return $this->user_dungeon_stage_history;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserDungeonStageHistory user_dungeon_stage_history = 2;</code>
     * @param \Msggamedata\MsgUserDungeonStageHistory[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserDungeonStageHistory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgUserDungeonStageHistory::class);
        $this->user_dungeon_stage_history = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgFriendDungeonFindHistory friend_dungeons = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFriendDungeons()
    {
        return $this->friend_dungeons;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgFriendDungeonFindHistory friend_dungeons = 3;</code>
     * @param \Msggamedata\MsgFriendDungeonFindHistory[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFriendDungeons($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgFriendDungeonFindHistory::class);
        $this->friend_dungeons = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgInfiniteDungeonHistory infinite_dungeon = 4;</code>
     * @return \Msggamedata\MsgInfiniteDungeonHistory
     */
    public function getInfiniteDungeon()
    {
        return $this->infinite_dungeon;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgInfiniteDungeonHistory infinite_dungeon = 4;</code>
     * @param \Msggamedata\MsgInfiniteDungeonHistory $var
     * @return $this
     */
    public function setInfiniteDungeon($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgInfiniteDungeonHistory::class);
        $this->infinite_dungeon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 5;</code>
     * @return \Msggamedata\MsgUserColossusDungeonStageHistory
     */
    public function getColossusStageHistory()
    {
        return $this->colossus_stage_history;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 5;</code>
     * @param \Msggamedata\MsgUserColossusDungeonStageHistory $var
     * @return $this
     */
    public function setColossusStageHistory($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserColossusDungeonStageHistory::class);
        $this->colossus_stage_history = $var;

        return $this;
    }

}

