<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSetMonsterCostume.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspSetMonsterCostume</code>
 */
class RspSetMonsterCostume extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserMonster user_monsters = 1;</code>
     */
    private $user_monsters;

    public function __construct() {
        \GPBMetadata\RspSetMonsterCostume::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserMonster user_monsters = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserMonsters()
    {
        return $this->user_monsters;
    }

    /**
     * Generated from protobuf field <code>repeated .msggamedata.MsgUserMonster user_monsters = 1;</code>
     * @param \Msggamedata\MsgUserMonster[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserMonsters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msggamedata\MsgUserMonster::class);
        $this->user_monsters = $arr;

        return $this;
    }

}

