<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSetOrUpdateUserMeta.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspSetOrUpdateUserMeta</code>
 */
class RspSetOrUpdateUserMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMeta user_meta = 1;</code>
     */
    private $user_meta = null;

    public function __construct() {
        \GPBMetadata\RspSetOrUpdateUserMeta::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMeta user_meta = 1;</code>
     * @return \Msggamedata\MsgUserMeta
     */
    public function getUserMeta()
    {
        return $this->user_meta;
    }

    /**
     * Generated from protobuf field <code>.msggamedata.MsgUserMeta user_meta = 1;</code>
     * @param \Msggamedata\MsgUserMeta $var
     * @return $this
     */
    public function setUserMeta($var)
    {
        GPBUtil::checkMessage($var, \Msggamedata\MsgUserMeta::class);
        $this->user_meta = $var;

        return $this;
    }

}

