<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspUpdateUserDungeonTicketCount.proto

namespace Msggamedata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msggamedata.RspUpdateUserDungeonTicketCount</code>
 */
class RspUpdateUserDungeonTicketCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     */
    private $count = 0;
    /**
     * Generated from protobuf field <code>uint64 expire_date = 2;</code>
     */
    private $expire_date = 0;

    public function __construct() {
        \GPBMetadata\RspUpdateUserDungeonTicketCount::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expire_date = 2;</code>
     * @return int|string
     */
    public function getExpireDate()
    {
        return $this->expire_date;
    }

    /**
     * Generated from protobuf field <code>uint64 expire_date = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireDate($var)
    {
        GPBUtil::checkUint64($var);
        $this->expire_date = $var;

        return $this;
    }

}

