<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TutorialStep.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\TutorialStep</code>
 */
class TutorialStep
{
    /**
     * Generated from protobuf enum <code>TutorialStepNULL = 0;</code>
     */
    const TutorialStepNULL = 0;
    /**
     * Generated from protobuf enum <code>TS_NewUser = 1;</code>
     */
    const TS_NewUser = 1;
    /**
     * Generated from protobuf enum <code>TS_GoToCapture = 10;</code>
     */
    const TS_GoToCapture = 10;
    /**
     * Generated from protobuf enum <code>TS_Capture = 20;</code>
     */
    const TS_Capture = 20;
    /**
     * Generated from protobuf enum <code>TS_Summon = 30;</code>
     */
    const TS_Summon = 30;
    /**
     * Generated from protobuf enum <code>TS_GoToSelectStage1 = 40;</code>
     */
    const TS_GoToSelectStage1 = 40;
    /**
     * Generated from protobuf enum <code>TS_SelectStage1 = 50;</code>
     */
    const TS_SelectStage1 = 50;
    /**
     * Generated from protobuf enum <code>TS_Battle1 = 60;</code>
     */
    const TS_Battle1 = 60;
    /**
     * Generated from protobuf enum <code>TS_RuneAndFeed = 70;</code>
     */
    const TS_RuneAndFeed = 70;
    /**
     * Generated from protobuf enum <code>TS_GoToSelectStage2 = 80;</code>
     */
    const TS_GoToSelectStage2 = 80;
    /**
     * Generated from protobuf enum <code>TS_SelectStage2 = 90;</code>
     */
    const TS_SelectStage2 = 90;
    /**
     * Generated from protobuf enum <code>TS_Battle2 = 100;</code>
     */
    const TS_Battle2 = 100;
    /**
     * Generated from protobuf enum <code>TS_ToBeCompleted = 110;</code>
     */
    const TS_ToBeCompleted = 110;
    /**
     * Generated from protobuf enum <code>TS_Completed = 120;</code>
     */
    const TS_Completed = 120;
}

