<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileIconUnlockType.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\UserProfileIconUnlockType</code>
 */
class UserProfileIconUnlockType
{
    /**
     * Generated from protobuf enum <code>UPIU_Default = 0;</code>
     */
    const UPIU_Default = 0;
    /**
     * Generated from protobuf enum <code>UPIU_BuyItem = 1;</code>
     */
    const UPIU_BuyItem = 1;
    /**
     * Generated from protobuf enum <code>UPIU_Like = 2;</code>
     */
    const UPIU_Like = 2;
}

