<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebEventPlayMode.proto

namespace Msggamedata;

/**
 * Protobuf enum <code>Msggamedata\WebEventPlayMode</code>
 */
class WebEventPlayMode
{
    /**
     * Generated from protobuf enum <code>WebEventPlayModeNULL = 0;</code>
     */
    const WebEventPlayModeNULL = 0;
    /**
     * Generated from protobuf enum <code>WEPM_Account_Level_Up = 1;</code>
     */
    const WEPM_Account_Level_Up = 1;
    /**
     * Generated from protobuf enum <code>WEPM_Use_Energy = 20;</code>
     */
    const WEPM_Use_Energy = 20;
    /**
     * Generated from protobuf enum <code>WEPM_Use_Arena_Ticket = 21;</code>
     */
    const WEPM_Use_Arena_Ticket = 21;
    /**
     * Generated from protobuf enum <code>WEPM_Get_Gem = 22;</code>
     */
    const WEPM_Get_Gem = 22;
    /**
     * Generated from protobuf enum <code>WEPM_Use_Gem = 23;</code>
     */
    const WEPM_Use_Gem = 23;
    /**
     * Generated from protobuf enum <code>WEPM_Get_Gold = 24;</code>
     */
    const WEPM_Get_Gold = 24;
    /**
     * Generated from protobuf enum <code>WEPM_Use_Gold = 25;</code>
     */
    const WEPM_Use_Gold = 25;
    /**
     * Generated from protobuf enum <code>WEPM_Get_Beyond_Stone = 26;</code>
     */
    const WEPM_Get_Beyond_Stone = 26;
    /**
     * Generated from protobuf enum <code>WEPM_Use_Beyond_Stone = 27;</code>
     */
    const WEPM_Use_Beyond_Stone = 27;
    /**
     * Generated from protobuf enum <code>WEPM_Get_Crystal = 28;</code>
     */
    const WEPM_Get_Crystal = 28;
    /**
     * Generated from protobuf enum <code>WEPM_Use_Crystal = 29;</code>
     */
    const WEPM_Use_Crystal = 29;
    /**
     * Generated from protobuf enum <code>WEPM_Get_Star_Essence = 30;</code>
     */
    const WEPM_Get_Star_Essence = 30;
    /**
     * Generated from protobuf enum <code>WEPM_Join_Clan = 31;</code>
     */
    const WEPM_Join_Clan = 31;
    /**
     * Generated from protobuf enum <code>WEPM_Get_Clan_Point = 32;</code>
     */
    const WEPM_Get_Clan_Point = 32;
    /**
     * Generated from protobuf enum <code>WEPM_Use_Clan_Point = 33;</code>
     */
    const WEPM_Use_Clan_Point = 33;
    /**
     * Generated from protobuf enum <code>WEPM_Buy_Energy = 34;</code>
     */
    const WEPM_Buy_Energy = 34;
    /**
     * Generated from protobuf enum <code>WEPM_Buy_Gold = 35;</code>
     */
    const WEPM_Buy_Gold = 35;
    /**
     * Generated from protobuf enum <code>WEPM_Buy_Gem = 36;</code>
     */
    const WEPM_Buy_Gem = 36;
    /**
     * Generated from protobuf enum <code>WEPM_Daily_First_Login = 37;</code>
     */
    const WEPM_Daily_First_Login = 37;
    /**
     * Generated from protobuf enum <code>WEPM_All_Complete_Bingo = 38;</code>
     */
    const WEPM_All_Complete_Bingo = 38;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Scenario_Battle = 100;</code>
     */
    const WEPM_Play_Scenario_Battle = 100;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Scenario_Battle_Normal = 101;</code>
     */
    const WEPM_Play_Scenario_Battle_Normal = 101;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Scenario_Battle_Hard = 102;</code>
     */
    const WEPM_Play_Scenario_Battle_Hard = 102;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Scenario_Battle_Extreme = 103;</code>
     */
    const WEPM_Play_Scenario_Battle_Extreme = 103;
    /**
     * Generated from protobuf enum <code>WEPM_Play_All_Day_Beyond_Stone_Dungeon_Battle = 110;</code>
     */
    const WEPM_Play_All_Day_Beyond_Stone_Dungeon_Battle = 110;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Beyond_Stone_Dungeon_Battle = 112;</code>
     */
    const WEPM_Play_Day_Beyond_Stone_Dungeon_Battle = 112;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Gold_Dungeon_Battle = 113;</code>
     */
    const WEPM_Play_Gold_Dungeon_Battle = 113;
    /**
     * Generated from protobuf enum <code>WEPM_Play_All_Day_Rune_Dungeon_Battle = 114;</code>
     */
    const WEPM_Play_All_Day_Rune_Dungeon_Battle = 114;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Friend_Dungeon_Battle = 115;</code>
     */
    const WEPM_Play_Friend_Dungeon_Battle = 115;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Rune_Dungeon_Battle = 116;</code>
     */
    const WEPM_Play_Day_Rune_Dungeon_Battle = 116;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Colossus_Dungeon_Battle = 117;</code>
     */
    const WEPM_Play_Colossus_Dungeon_Battle = 117;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Infinite_Battle = 120;</code>
     */
    const WEPM_Play_Infinite_Battle = 120;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Scenario_Battle_Continent1 = 121;</code>
     */
    const WEPM_Play_Scenario_Battle_Continent1 = 121;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Scenario_Battle_Continent2 = 122;</code>
     */
    const WEPM_Play_Scenario_Battle_Continent2 = 122;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Scenario_Battle_Continent3 = 123;</code>
     */
    const WEPM_Play_Scenario_Battle_Continent3 = 123;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Arena_Battle = 130;</code>
     */
    const WEPM_Play_Arena_Battle = 130;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Mon = 150;</code>
     */
    const WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Mon = 150;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Tue = 151;</code>
     */
    const WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Tue = 151;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Wed = 152;</code>
     */
    const WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Wed = 152;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Thu = 153;</code>
     */
    const WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Thu = 153;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Fri = 154;</code>
     */
    const WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Fri = 154;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Sat = 155;</code>
     */
    const WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Sat = 155;
    /**
     * Generated from protobuf enum <code>WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Sun = 156;</code>
     */
    const WEPM_Play_Day_Beyond_Stone_Dungeon_Battle_Sun = 156;
    /**
     * Generated from protobuf enum <code>WEPM_Get_Capture_Point = 160;</code>
     */
    const WEPM_Get_Capture_Point = 160;
    /**
     * Generated from protobuf enum <code>WEPM_Start_Clan_Battle = 170;</code>
     */
    const WEPM_Start_Clan_Battle = 170;
    /**
     * Generated from protobuf enum <code>WEPM_Start_CVC_Battle = 171;</code>
     */
    const WEPM_Start_CVC_Battle = 171;
    /**
     * Generated from protobuf enum <code>WEPM_Attendance_Clan = 172;</code>
     */
    const WEPM_Attendance_Clan = 172;
    /**
     * Generated from protobuf enum <code>WEPM_Warm_Up_Monster = 200;</code>
     */
    const WEPM_Warm_Up_Monster = 200;
    /**
     * Generated from protobuf enum <code>WEPM_Evolution_Monster = 201;</code>
     */
    const WEPM_Evolution_Monster = 201;
    /**
     * Generated from protobuf enum <code>WEPM_Beyond_Monster = 202;</code>
     */
    const WEPM_Beyond_Monster = 202;
    /**
     * Generated from protobuf enum <code>WEPM_Upgrade_Rune = 203;</code>
     */
    const WEPM_Upgrade_Rune = 203;
    /**
     * Generated from protobuf enum <code>WEPM_Feed_Item = 204;</code>
     */
    const WEPM_Feed_Item = 204;
    /**
     * Generated from protobuf enum <code>WEPM_Upgrade_Monster_Skill = 205;</code>
     */
    const WEPM_Upgrade_Monster_Skill = 205;
    /**
     * Generated from protobuf enum <code>WEPM_Super_Evolution_Monster = 206;</code>
     */
    const WEPM_Super_Evolution_Monster = 206;
    /**
     * Generated from protobuf enum <code>WEPM_Find_Nezz = 300;</code>
     */
    const WEPM_Find_Nezz = 300;
    /**
     * Generated from protobuf enum <code>WEPM_Lobby_Reward = 301;</code>
     */
    const WEPM_Lobby_Reward = 301;
    /**
     * Generated from protobuf enum <code>WEPM_Set_Free_Monster = 302;</code>
     */
    const WEPM_Set_Free_Monster = 302;
    /**
     * Generated from protobuf enum <code>WEPM_Send_Friend_Gift = 310;</code>
     */
    const WEPM_Send_Friend_Gift = 310;
    /**
     * Generated from protobuf enum <code>WEPM_Capture_Monster = 320;</code>
     */
    const WEPM_Capture_Monster = 320;
    /**
     * Generated from protobuf enum <code>WEPM_Capture_Rare_Monster_In_Continent1 = 321;</code>
     */
    const WEPM_Capture_Rare_Monster_In_Continent1 = 321;
    /**
     * Generated from protobuf enum <code>WEPM_Capture_Rare_Monster_In_Continent2 = 322;</code>
     */
    const WEPM_Capture_Rare_Monster_In_Continent2 = 322;
    /**
     * Generated from protobuf enum <code>WEPM_Capture_Rare_Monster_In_Continent3 = 323;</code>
     */
    const WEPM_Capture_Rare_Monster_In_Continent3 = 323;
    /**
     * Generated from protobuf enum <code>WEPM_Get_Monster = 330;</code>
     */
    const WEPM_Get_Monster = 330;
    /**
     * Generated from protobuf enum <code>WEPM_Summon_Monster_By_Revives = 340;</code>
     */
    const WEPM_Summon_Monster_By_Revives = 340;
    /**
     * Generated from protobuf enum <code>WEPM_Summon_Monster = 350;</code>
     */
    const WEPM_Summon_Monster = 350;
    /**
     * Generated from protobuf enum <code>WEPM_Summon_Monster_By_Soulstone = 351;</code>
     */
    const WEPM_Summon_Monster_By_Soulstone = 351;
    /**
     * Generated from protobuf enum <code>WEPM_Summon_Monster_By_Egg = 352;</code>
     */
    const WEPM_Summon_Monster_By_Egg = 352;
    /**
     * Generated from protobuf enum <code>WEPM_Summon_Monster_From_Gacha_Shop = 353;</code>
     */
    const WEPM_Summon_Monster_From_Gacha_Shop = 353;
}

